### ISSUE TITLE
People skill - if someone simply asks "Who reports to" the bot should follow up and ask for a name

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#1002]
## Version
4.13

## Describe the bug
When someone simply asks a question without an entity, it should trigger a new flow to ask for the name to search.

## To Reproduce
1. Ask "who reports to"

## Expected behavior
Trigger a flow to disambiguate who the person is about.

**Comment by lauren-mills** [comment]
Moving to a note in the backlog
