### ISSUE TITLE
Teams: Duplicate copies of identical README.md in different language packages

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#1041]
In splitting the Teams component package out to separate .NET and JS packages, the README.md to be included in the package was moved up to a common directory. This inadvertently broke the packaging pipeline as it couldn't locate the file anymore, as it expected to placed in the project root. This was ultimately addressed in #1040 by creating separate copies.

We should evaluate what our story is for files that may ultimately be identical between different language versions of the same package, e.g. READMEs, schema files, etc. We may no-op and decide separate copies is the right path, but this issue ultimately is for tracking resolution to that question, and if applicable, any follow-up action to address the duplicate copies that now exist.

**Comment by ryanlengel** [comment]
One option here is that we leave the source code in the repo in an easy to maintain state and use the publishing pipelines to handle these behaviors. In this case keep a single README in the common directory, but have a step in the pipelines that copies these into the correct location on the build server before packaging up.

**Comment by ryanlengel** [comment]
Related to #1041

**Comment by ryanlengel** [comment]
Related to #673
