### ISSUE TITLE
Enterpise Assistant template does not open [error]

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#1058]
## Version
Version:  2.0.0-nightly.240913.4390cd8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Describe the bug
Selecting Enterprise template for today, does not open shows Error message (did show load, etc steps)

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/116685822-3cd89880-a9b3-11eb-967b-851236d853ee.png)

**Comment by sgellock** [comment]
Shiproom - approved
