### ISSUE TITLE
Function bots don't pick up LUIS app ID

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botframework-components#1063]
## Describe the bug
Function bots do not appear to pick up the LUIS app ID from app settings despite the data being populated in the field.

## Version
Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

0. Make sure you have the [Azure core tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash) installed
1. Create a .net function bot
2. Create a provision for the bot
3. Create an intent 
4. Publish the bot
5. Start the bot and try to invoke the intent

## Expected behavior
You shouldn't be able to start the bot without adding the LUIS info

## Screenshots
App settings standard view:
![image](https://user-images.githubusercontent.com/50158775/116492713-d25c1700-a851-11eb-88a8-fab6e80db7e5.png)

App settings advanced view:
![image](https://user-images.githubusercontent.com/50158775/116492737-df790600-a851-11eb-8d12-f77dd71fa53b.png)

![image](https://user-images.githubusercontent.com/50158775/116492477-35997980-a851-11eb-8475-0787a2153f18.png)
![image](https://user-images.githubusercontent.com/50158775/116492589-7a251500-a851-11eb-9523-642205921959.png)

## Additional context
In the web app version Composer will have an error saying you can't start the bot without updating the LUIS data. I don't know if that check is missing here, or if something else is going on.

**Comment by sgellock** [comment]
Shiproom - @benbrown can you work the build issue?

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by sgellock** [comment]
Shiproom - this is required for RC9 of the new bot templates

**Comment by Virtual-Josh** [comment]
This issue is still occurring with today's build:
Version:  2.0.0-nightly.243234.8264ac4
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

![image](https://user-images.githubusercontent.com/50158775/117376215-89c1e080-ae85-11eb-8360-4a015fcf42e6.png)
