### ISSUE TITLE
Orphaned Teams schema file

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#1067]
It looks like the file/folder in the screenshot below ended up in the wrong location:

![image](https://user-images.githubusercontent.com/1139814/116940659-1f116a80-ac23-11eb-8699-af86897f1009.png)

**Comment by peterinnesmsft** [comment]
@joshgummersall I think this came out of the JS addition. Can you speak to this?

**Comment by joshgummersall** [comment]
Yeah, all the schema files should exist under the relevant language. I'll resolve this.

**Comment by peterinnesmsft** [comment]
Just to keep up-to-date on current status of this for vis - The `Teams.OnTeamHardDeleted` trigger schema is ultimately missing from both .NET and JS packages. Impact of this is that the trigger won't appear in Composer. We are content with this being post-R13.
