### ISSUE TITLE
Migrate cards used in generators use the AdaptiveCards package

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#1083]
Now that we have the `Microsoft.Bot.Components.AdaptiveCards` package we should lean on it for our other components that use Adaptive Cards so they share a standardized method of composing them.

**Comment by clearab** [comment]
@ryanlengel Why is this one labeled "evaluate"? Do you want to create issues for each package individually? This is definitely work we'll want to do.

**Comment by ryanlengel** [comment]
Just wording, I've updated the title. But we should weigh using this package against the default experience in Composer for Adaptive Cards and ensure that they are a cohesive experience - rather than just adding dependencies to this package and being done with it.
