### ISSUE TITLE
EA skills interrupt themselves. Breaks new meeting flow 

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-components#1106]
When you are creating a new meeting in calendar and respond with an utterance that Orchestrator detects as a calendar intent, it restarts the skill and loses your current progress.

Example:
- user: New meeting
- bot: What should I set the title to?
- user: Team Meeting                    <--- This triggers the orchestrator interruption logic because it scores highly for calendar and restarts the skill

The fix for this is to add a property tracking the current skill and not allow that skill to interrupt itself, but only allow interruptions for other intents.

**Comment by sgellock** [comment]
Shiproom - lets bottom out a solution for this and then assess.  Interruption can be challenging, so I want to ensure we have time to vet a fix.

**Comment by sgellock** [comment]
Shiproom - fix was tested in the PBX team's test env.  approved.
