### ISSUE TITLE
Trigger names for Adaptive Card packages are too long

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#1110]
The trigger names for the Adaptive Cards package are all of the form "Microsoft.Bot.Component.AdaptiveCard.<triggerName", which means they look like this when you add them:

![image](https://user-images.githubusercontent.com/1139814/117887748-0974f400-b266-11eb-8a62-817e0bd3df26.png)

We need to rename all of these to be just "AdaptiveCard.<triggerName", or potentially just "ac.<triggerName>".

**Comment by lauren-mills** [comment]
@clearab - Can you assign an owner to this issue?

**Comment by cwhitten** [comment]
There is a bug in Composer, see https://github.com/microsoft/BotFramework-Composer/issues/7943

**Comment by a-b-r-o-w-n** [comment]
This has been addressed in Composer via the Trigger UI Schema microsoft/botframework-composer#8190.

**Comment by clearab** [comment]
@a-b-r-o-w-n : What's the outcome of that change? For our published packages, would we need to add the new property in our uiSchema files? Is this change independent of fixing the bug that @cwhitten linked to?

**Comment by a-b-r-o-w-n** [comment]
I haven't looked at all of the ui schema files for the components, but the Composer change uses the `label` property in the `trigger` section of the UI schema. For example: https://github.com/microsoft/botframework-components/blob/main/packages/AdaptiveCards/Schemas/Microsoft.Bot.Components.OnActionExecute.uischema#L16

So the component author has the ability to set a default value for what the user sees in the flow + form in Composer.

**Comment by clearab** [comment]
@lauren-mills I believe this means that to achieve the desired output (not including the fully qualified name as the trigger name), we'll need to update the ui-schema files across our packages to make sure they are using the `label` property. I took a quick glance through the packages and there seems to be a mix.

**Comment by lauren-mills** [comment]
Triggers look like this in latest Composer build, so I think we're good to close this.

![image](https://user-images.githubusercontent.com/27976702/124177043-8e111100-da64-11eb-82eb-4aebd480b442.png)
