### ISSUE TITLE
Ensure Adaptive Cards Package reaches GA level of support

### ISSUE THREAD

**Issue by kaerm** [microsoft/botframework-components#1111]
The newly created Adaptive Cards package should go through a quality check to ensure it is ready to be used:
- [ ] test all of the functionalities of the package 
- [ ] create documentation explaining the functionality
- [ ] create samples that use the package
- [ ] #1083: once the above points are completed, the AC package should be added as a dependency for other packages that are creating Adaptive Cards. For example: Calendar, People, Teams (samples), Enterprise Assistant, Core Assistant

**Comment by ryanlengel** [comment]
I'm tracking the 4th item in #1083 and updated the parent with it
