### ISSUE TITLE
Default static directory to wwwroot instead of www for .NET Functions-based bots

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#1112]
In response to https://github.com/microsoft/BotFramework-Composer/issues/7776, the decision was made in shiproom to update the static files root directory across the board to wwwroot. In response to this decision, the .NET Functions templates in the base adaptive generator need to be updated to use wwwroot instead of www.

**Comment by sgellock** [comment]
Shiproom - approved.  P0 scenario enablement.
