### ISSUE TITLE
No templates are available except QnA

### ISSUE THREAD

**Issue by jh2kimgit** [microsoft/botframework-components#1131]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lauren-mills** [comment]
Hi @jh2kimgit, can you please provide more information so we can assist? 

Are you using Composer, if so, what version? Can you include a screenshot of what you're experiencing?

If you are not using Composer, can you explain the process you are following?

**Comment by lauren-mills** [comment]
Closing this due to a lack of information. Please reopen as needed.
