### ISSUE TITLE
Update an existing Adaptive Card - 'activityId' cannot be null error

### ISSUE THREAD

**Issue by Bolleman** [microsoft/botframework-components#1153]
## Describe the bug

When using the "Update an existing Adaptive Card" action, it throws the error: 'activityId' cannot be null.
Also, there is a typo in the default for the Activity ID setting.  It is '=turn.activity.replyTo' when I believe the author likely meant '=turn.activity.replyToId'

## Version

Microsoft.Bot.Components.AdaptiveCards 1.0.0
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce
Here is the configuration.  
```json
{
    "$kind": "Microsoft.Bot.Components.UpdateAdaptiveCard",
    "$designer": {
        "id": "Zr7TzQ"
    },
    "template": {
        "type": "AdaptiveCard",
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.2",
        "body": [
            {
                "type": "TextBlock",
                "text": "${textData}",
                "wrap": true
            }
        ]
    },
    "activityId": "=dialog.activityId",
    "data": {
        "textData": "- This \r- One \r"
    }
}
```
The standard Composer Update Activity action works fine with the same activityId, e.g. 

```json
{
    "$kind": "Microsoft.UpdateActivity",
    "$designer": {
        "id": "QIw5n9"
    },
    "activity": "${UpdateActivity_Activity_QIw5n9()}",
    "activityId": "=dialog.activityId"
}
```
## Expected behavior

update card with no error

**Comment by Stevenic** [comment]
@Bolleman thanks for catching type-o.  As for the exception are you testing with the emulator by chance?  The emulator doesn't support "update" calls so the `UpdateActivity` action is likely just doing a send in that case. I can verify that they behave the same way but be aware you won't see it replace the card when using the emulator.

**Comment by Bolleman** [comment]
@Stevenic thanks for looking into it.  I'm using Teams for testing.  Since the standard Update Activity works fine as noted I'll just use that and create the card as a separate step.  So no big deal to close this issue if it is working fine for others.
![image](https://user-images.githubusercontent.com/8999611/123165277-e2930b80-d428-11eb-8d35-9dcf87fcc2ae.png)

**Comment by thomas-chung** [comment]
Thanks @Bolleman! We are going to close the issue now since we have a fix going in and there is an existing work around.

**Comment by dawwa** [comment]
@thomas-chung, would you please help clarify the workaround? it is still happening https://github.com/microsoft/BotFramework-Composer/issues/8651
