### ISSUE TITLE
[NewTemplateRequest] Bot to Teams Handoff template request

### ISSUE THREAD

**Issue by aparnaji** [microsoft/botframework-components#1154]
Can I get  template for agent handoff , composer Bot to microsoft teams

**Comment by lauren-mills** [comment]
Thanks for your request! We will add this request to the backlog and evaluate it for inclusion in a future release.

Can you add more information about what features you would like the template to include or the problem you would like us to solve so we can triage the request?

**Comment by aparnaji** [comment]
Need this for handoff to Agent if required in Bot, Should have the ability to pass the transcript to Agent  for the reference. Agents will be in teams. if possible skill based routing
