### ISSUE TITLE
Generated bots can't run in dotnet 5.0

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botframework-components#1160]
## Describe the bug

A newly generated emtpy bot seems to be pinned to target dotnet 3.1, so that if have dotnet 5.0 installed, it fails to run. 
![image](https://user-images.githubusercontent.com/3829387/122903966-7cec4400-d382-11eb-8568-9a62536f6730.png)

## Version

BF Composer 2.0

## To Reproduce

0. Install dotnet 5.0 (**install in a fresh env without 3.1 installed**)
1. Create a new bot
2. dotnet run -p botname.csproj in that folder

## Additional context

I can maually work around it, by updating the targeting framework to net5.0, but it's annoying for users to do that.  We should either auto detect and generate based on dotnet version, or have user to choose version to generate.

**Comment by tracyboehrer** [comment]
Some analysis and planning will be required for this.  5.0 support from SDK might be an R15 goal, and it is undetermined if this works.  Mullins states "it may or may not work".

@benbrown If the generator has to support an option for this, it would take more than a generator change.  I rather doubt an auto-detect will work, as it needs to be the desired deployed target, not what's on the devs local machine.

**Comment by boydc2014** [comment]
> Some analysis and planning will be required for this. 5.0 support from SDK might be an R15 goal, and it is undetermined if this works. Mullins states "it may or may not work".
> 
> @benbrown If the generator has to support an option for this, it would take more than a generator change. I rather doubt an auto-detect will work, as it needs to be the desired deployed target, not what's on the devs local machine.

Yes, an auto-detect on local might not make sense.

One thing i'm pretty sure is that, the way the "targetFramework" is set today will gurrantee it won't work. If someone has 5.0 installed and stated that it worked, that's because they also have 3.0 installed.
