### ISSUE TITLE
Cannot view templates in composer

### ISSUE THREAD

**Issue by mukundhareddy1996** [microsoft/botframework-components#1237]
I am unable to see any other templates like - echo bot, empty bot, and others 
By default, I am getting launched with Core Bot, when I click "request for more templates" that is launching here 

What I already did:
--> Reinstalled the composer 
--> updated to the latest version 
![image](https://user-images.githubusercontent.com/22534728/127289937-1a15b7ca-7f79-4860-bc37-5d1fa724f6c1.png)
![image](https://user-images.githubusercontent.com/22534728/127290047-b433dc50-7768-4231-b5b6-3e72ec72fd7a.png)

**Comment by peterswimm** [comment]
Do you have NPM installed on your machine? If so, perhaps it is being blocked by firewall policy?

**Comment by taicchoumsft** [comment]
Related to [Composer#8188](https://github.com/microsoft/BotFramework-Composer/issues/8188)

**Comment by mukundhareddy1996** [comment]
I have NPM installed in my machine and not it was not blocked by a firewall aswell.
 
Resolved:
-------------
I have done reinstallation around 2-3 times. surprisingly it worked the last time. 
The issue got resolved.
