### ISSUE TITLE
Bot Composer dotnet core enterprise assistant build size comes to 1Gb which is containing many libraries which are actually not added

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/botframework-components#1238]
## Describe the bug

Bot Composer dotnet core enterprise assistant build size comes to 1Gb which is containing many libraries which are not added by me and not used at all.

## Version

2.0.0

## Browser

Desktop version

- [ 2.0.0] Electron distribution

## OS

Windows OS

## To Reproduce

1. Create a Enterprise Assistant sample bot
2. publish it to Azure or create a pipeline build artifact.
3. check the wwwroot folder in azure app service kudu console or pipeline published artifact size
4. 1Gb file is created with many libraries which are not referenced and not used.

## Expected behavior

appropriate size of build.

## Screenshots

![image](https://user-images.githubusercontent.com/24915474/127269480-962f1715-04d3-41a7-9d4b-f34369a45369.png)

In above screenshot it contains around 466 items which is quite a high and app service deployment from pipeline fails several times due to this generous size.

Is there a way to reduce the size and add libraries which are only used in solution?

I even tried to use the preview version of pipeline in this link. which creates a build of 2GB and the devops publish is failing due to this.

**Comment by taicchoumsft** [comment]
Hey @lauren-mills , could you take a look at this one? Thanks

**Comment by taicchoumsft** [comment]
Hey @SSanjeevi , can you sort by size, and take a screenshot or dump of the largest items in the list?  Thanks @SSanjeevi

**Comment by SSanjeevi** [comment]
Hi @taicchoumsft you are right the model folder file is the one having more memory, please check the screenshots below.

![image](https://user-images.githubusercontent.com/24915474/127440580-1a622f3b-e378-4eb2-9a3c-1f0ce3f8f1e3.png)

![image](https://user-images.githubusercontent.com/24915474/127440614-b06edb0e-5f58-47df-8808-b04bbed84d0b.png)

But we included the model files after seeing your suggestion to include them for the issue in this link: 

![image](https://user-images.githubusercontent.com/24915474/127441073-70f61725-d5e0-4997-9bf3-89b894fb0434.png)

https://github.com/microsoft/BotFramework-Composer/issues/7892#issuecomment-846443555

we also faced that issue when deploying the bot it didn't work on multilingual instance. Now what is the work around or solution for this? to solve both the problems.

**Comment by taicchoumsft** [comment]
Thanks @SSanjeevi , I do remember this.  

The Orchestrator team have recently been working on a new set of quantized models that offer similar performance but with a 2/3rd reduction in size. 

We propose to switch to those models if you find the performance satisfactory for your usecase.  They will greatly reduce the burden on you 

Here's how you can try the new models out:
1) Upgrade to Composer v2.1 if you haven't already done so
2) Load your project that is using Orchestrator and click `Start Bot` at least once. 
3) Open your Bot Settings, and enable the `Advanced Settings View(json)` (or just open the `settings/appsettings.json` file from a file editor). You will see a new section here for Orchestrator that looks like this:
```
  "orchestrator": {
    "model": {
      "en_intent": "pretrained.20200924.microsoft.dte.00.06.en.onnx",
      "multilingual_intent": "pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual.onnx"
    }
  },
```
4) Please change the en_intent model to `pretrained.20210521.microsoft.dte.01.06.int.en.onnx` and the `multilingual_intent" model to `pretrained.20210608.microsoft.dte.01.06.int.unicoder_multilingual.onnx`.  
```
  "orchestrator": {
    "model": {
      "en_intent": "pretrained.20210521.microsoft.dte.01.06.int.en.onnx",
      "multilingual_intent": "pretrained.20210608.microsoft.dte.01.06.int.unicoder_multilingual.onnx"
    }
  },
```
5) Start Bot *and* Publish your bot again to test the results and push the correct models to the `models` folder.
6) You can checkin the new models after publishing

Please let us know if the model sizes and language performance of the new models are satisfactory for you.

Thanks @SSanjeevi .

**Comment by SSanjeevi** [comment]
@taicchoumsft - is there a way to try this new model size in the sample pipeline shared [here](https://docs.microsoft.com/en-us/composer/how-to-cicd), do you see any update in this pipeline for this change to work from that build to use latest 2/3 of the model size.

I tried updating the project file as suggested by you and i see the same size build artifact generated and the model is still referring old ones.

**Comment by SSanjeevi** [comment]
@taicchoumsft Thank you so much 💯 👍 🥇 
It worked.

**Comment by SSanjeevi** [comment]
Closing this issue.
