### ISSUE TITLE
Core Assistant Bot for Node.js

### ISSUE THREAD

**Issue by anuragsen** [microsoft/botframework-components#1252]
Hey Team,

Do you have any templates (in development maybe) for Core Assistant Bot for Node.js? I would love to try and get my hands on one.

Edit: using Bot FW Composer v2.1.0

Thanks!

**Comment by LeeParrishMSFT** [comment]
Thanks for the feedback. I've provided this feedback to program management for consideration in a future release, but there are no current plans for additional templates at this time. 

This would be a great community project if someone were to want to jump in and build one out.
