### ISSUE TITLE
bot gives 501 response to composeExtension/submitAction invoke from Teams message extension

### ISSUE THREAD

**Issue by Bolleman** [microsoft/botframework-components#1275]
## Describe the bug

The bot is responding to a composeExtension/submitAction invoke with a "501 Not Implemented" which is causing Teams to display a modal window with the following message: "Unable to reach app. Please try again.".   Otherwise it is working fine as the invoke triggers the Messaging extension - on submit action and actions are processed as expected from there.  

I noticed that this issue goes away if the dialog uses at least one of the Composer Teams message extension standard responses (e.g. Send messaging extensions attachment(s) response).   The Teams [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet%2Cdotnet-1) states that it is OK to not respond to the invoke, but I guess they at least need a 200 response.

So the question is, is their any way to get the bot to send a 200 response to the composeExtension/submitAction invoke without using one of the Teams messaging extension response types?  I'm not sure if this is a bug or I'm just missing something.  Thanks for any help!

Update:  after further testing I've also noticed that the same problem (501 response, Teams says unable to reach App) occurs when the bot receives an invoke of name "adaptiveCard/action" as a result of an action.execute.  So maybe this is a more general Composer issue.  

## Version

Composer 2.1.1
Microsoft.Bot.Components.Teams 1.1.2

## To Reproduce

```
{
      "$kind": "Teams.OnMESubmitAction",
      "$designer": {
        "id": "z4jSBP",
        "name": "Messaging extension - on submit action"
      },
      "actions": [
        {
          "$kind": "Teams.SendMessageToTeamsChannel",
          "$designer": {
            "id": "O5fU3F"
          },
          "teamsChannelId": "=turn.activity.channelData.channel.id",
          "activity": "${TeamsSendMessageToTeamsChannel_Activity_O5fU3F()}",
          "activityIdProperty": "dialog.activityId",
          "conversationReferenceProperty": "dialog.threadReference"
        }
      ],
      "commandId": "configureThread"
    }
```
## Expected behavior

200 response

**Comment by clearab** [comment]
All invokes require at least an http 200 response, so I believe in both cases what is happening is the Teams client waits for a response, then times out and throws the 501 when no response is received. We're missing default 200 responses in this package when no response is required, and we unfortunately also don't currently have a generic "send an invoke response" action.

As a workaround, for the first invoke you should be able to use any messaging extension response, or the "Respond to an action.execute" action from the Adaptive Cards package. The Teams client should ignore any body in the response to the submitAction, and just move on.

For the second, the "Respond to an action.execute" action in the Adaptive Cards package should be the right invoke response.

**Comment by clearab** [comment]
To expand a bit on the adaptiveCard/action invoke, there are four valid responses - a 200 w/no body, a message, a new adaptive card, or an auth challenge. The adaptive cards package models the message and adaptive card responses, but not the empty or the auth responses. If you want to send either the empty or auth responses, you'd unfortunately need to create custom actions to do so.

**Comment by Bolleman** [comment]
That makes perfect sense and should do the trick. Thanks for the quick response Andrew!

**Comment by Bolleman** [comment]
Finally was able to try this out.  For the response to the message extension submit, I tried several different Teams package actions.   None of the message extension actions worked without generating some unwanted side-effect, but the "Send tab card response" action did the trick.   Also, using the action.execute response from the Adaptive cards package results in the following error "SendActionExecuteResponse('=dialog.card'): should only be called in repsonse to 'invoke' activities with a name of 'adaptiveCard/action'".  Anyway, everything is working now, thanks again for the workaround suggestion.
