### ISSUE TITLE
IVR Chatbot using MS Composer

### ISSUE THREAD

**Issue by sathwikkrishna** [microsoft/botframework-components#1292]
Hi, I'm creating an IVR chatbot using MS composer, wherein a particular dialog I need to take 16 digits(Card Number) user input either both by voice or by keypad. In composer, I created a user input activity to take the input but it was breaking for the first number, for example, my card number is 9876543210123456 as soon as I typed 9 or spoke out 9 it is taking that particular only 9 as input and validating it, instead of all 16 digits.

Is this feature available in Composer?

Can anyone please help me solve this? 
Thanks in advance.

**Comment by carlosscastro** [comment]
@goldenwitch could you provide info @sathwikkrishna about how to achieve this scenario?

**Comment by msomanathan** [comment]
@goldenwitch Could you please help provide info about how to enable the customer's scenario? Thanks!

**Comment by goldenwitch** [comment]
Ah I've been @'d!

@sathwikkrishna we currently support this via the Telephony package
https://github.com/microsoft/botframework-components/tree/main/packages/Telephony#Aggregate-DTMF-Input-(n)

The above documentation is about using the Telephony package to collect a fixed length input. I believe the current version only supports using dial pad but has the aggregation behavior you are looking for.

This functionality should be available in https://www.nuget.org/packages/Microsoft.Bot.Components.Telephony/1.0.0-preview.20210816.6bc6617

Just between us here(read: the entire internet), we are looking at an updated version with broader versions of this functionality.

**Comment by mrivera-ms** [comment]
This issue has been replied to.
