### ISSUE TITLE
Direct Line Integration and Wakeup Keyword

### ISSUE THREAD

**Issue by fidelitymobileorg** [microsoft/botframework-components#1313]
Hi,

We hope this message finds you all well and healthy.

We didn't find the following resources in the composer documentation:

What is the procedure to perform the Direct Line integration of a Composer Core Assistant?

What is the step by step to create a Wakeup Keyword by voice in Composer?

**Comment by fidelitymobileorg** [comment]
@ryanlengel can help?

**Comment by ryanlengel** [comment]
Hi @fidelitymobileorg, thank you for opening this issue. Please refer to the following documentation:
- Direct Line integration: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directline?view=azure-bot-service-4.0
- Custom keyword: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/custom-keyword-basics?pivots=programming-language-csharp

For further product behavior, how-to, or general understanding questions, please use StackOverflow.

https://stackoverflow.com/search?q=bot+framework
