### ISSUE TITLE
Invalid DateTime in GroupEventsByDate - Graph Helper

### ISSUE THREAD

**Issue by casperhuijsman** [microsoft/botframework-components#1315]
## Describe the bug

While testing the Composer Calendar skill template we experienced the following behaviour.
If the browser settings are set to en-US, the date will display.
If the browser setting is not en-US, the date is not a valid DateTime.

Tested in both Edge and Chrome and this happens consistently with MS Teams and DirectLine.

## Version

Composer version 2.1.2
SDK version 4.15.2

## To Reproduce

Deploy the calendar template and use any browser and a Teams or Directline channel.

Edge
Change the browser settings of Edge to have English - English as top language > Schedule is shown properly in both DirectLine and Teams
Change the browser settings of Edge and replace English for another language like English (United Kingdom) > clear browser cache > DateTime is not a valid DateTime

Chrome
Change the language settings and select English (United States) as 'this language is used to display the Google Chrome UI' > Schedule is shown properly in both DirectLine and Teams
Change the 'this language is used to display the Google Chrome UI' for another language like English (United Kingdom) > clear browser cache > DateTime is not a valid DateTime

## Expected behavior
Independend of the user Language preferences the DateTime should be parsed correctly

## Screenshots

Teams example with English United States Edge
![Setting_englishamericanteams](https://user-images.githubusercontent.com/82145710/159278634-b38a5aee-2817-4b47-811c-7c2c4c433317.png)

Teams example with English United Kingdom Edge
![Setting_englishteams](https://user-images.githubusercontent.com/82145710/159278653-aa79a8f7-56ee-4efa-b09d-a4b71c8bc005.png)

DirectLine example with English United States Edge
![Setting_englishamerican](https://user-images.githubusercontent.com/82145710/159278827-94601b41-8552-4ce2-a6d2-aa911d3dfc8a.png)

DirectLine example with English United Kingdom Edge
![Setting_english](https://user-images.githubusercontent.com/82145710/159278811-76fac692-9d10-44a7-bdbd-5e3319338627.png)

## Additional context
This issue seems to be related to the line 89 in [GroupEventsByDate](https://github.com/microsoft/botframework-components/blob/main/packages/Graph/Actions/Helpers/GroupEventsByDate.cs)
 events = eventsProperty.Where(ev => ev.IsAllDay == false && DateTime.Parse(ev.Start.DateTime).Date == dt.Date).ToArray(),

Consider using CultureInfo.InvariantCulture

Besides, this method also creates issues when creating an event. Also here changing the language preferences will resolve the issue of creating an event. Yet again parsing of the date is taking place in this method
https://github.com/microsoft/botframework-components/blob/main/packages/Graph/Actions/Event/CreateEvent.cs

**Comment by ramfattah** [comment]
Hi @casperhuijsman, I'm investigating this.

**Comment by casperhuijsman** [comment]
Hi @ramfattah. Great! Any updates on your findings?

**Comment by ramfattah** [comment]
Hi @casperhuijsman, thanks for following up.

Have you tried adding multiple language support to see if you are still facing the issue? Sharing this [documentation](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language?tabs=v2x) regarding setting locale in Composer.

Try adding your locale in Composer and let me know if this worked. Thanks.

**Comment by ramfattah** [comment]
@casperhuijsman thanks for this detailed response, I will check with the engineering team regarding this.

**Comment by casperhuijsman** [comment]
@ramfattah Great news! I hope this can be resolved soon

**Comment by casperhuijsman** [comment]
@ramfattah Can you shine some light on the timeline? Without this issue resolved we'll not launch our bot

**Comment by ramfattah** [comment]
Hey @casperhuijsman, 

We are still investigating this issue as no timeline is available at the moment.
I will report back once we have updates. 

Thank you for your patience.

**Comment by ryub3n** [comment]
I have the same issue.

**Comment by casperhuijsman** [comment]
@ramfattah Since you are working on this. Could you give an estimation when you expect the issue to be adressed?

**Comment by ramfattah** [comment]
@casperhuijsman, thanks for following up. I will try to post an update before EOD today.

**Comment by ramfattah** [comment]
@casperhuijsman 

update: I was able to reproduce this issue using the [Enterprise Calendar Bot](https://docs.microsoft.com/en-us/composer/templates/enterprise-calendar-tutorial). 

`English (United State)` seems to work as expected, but when switched to another locale, ex: `English (United Kingdom)` the date is displayed as: 
![image](https://user-images.githubusercontent.com/38049078/163235164-c613d29a-b00b-401e-a45e-3e1fbf840315.png)

Additional info:

* This is w/out adding additional locale in the Composer bot.
* Unable to repro using built-in [Date or Time prompt](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#:~:text=the%20prompt%20field.-,Date%20or%20time%20input,-The%20DateTimeInput%20sample) in Composer. Only in Enterprise Template using Microsoft Graph API.

**Comment by ryub3n** [comment]
@ramfattah , any update on this issue? What did the engineering team say regarding @casperhuijsman's solution?

**Comment by ramfattah** [comment]
Hey @ryub3n

Thanks for following up. There is a PR for this and it's currently being worked on https://github.com/microsoft/botframework-components/pull/1326

**Comment by casperhuijsman** [comment]
I noticed the commit is approved and merged. When do you expect to release the fix?

**Comment by ramfattah** [comment]
Closed due to PR https://github.com/microsoft/botframework-components/pull/1326

It will probably be published next week.

**Comment by ryub3n** [comment]
@ramfattah , how to update the solution with the fixes?

**Comment by ramfattah** [comment]
Please update `Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime` to version 4.16.0 in Composer
![image](https://user-images.githubusercontent.com/38049078/166076912-489a6686-eae6-4d64-b39e-7d8ea4d435d6.png)

**Comment by ryub3n** [comment]
@ramfattah , I do not see the option to update.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/24279903/166223699-a7f401de-c975-4611-a12e-c6b21610b000.png">

**Comment by ramfattah** [comment]
Hi @ryub3n 

Here are the steps I took to upgrade `Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime` package:
1) Open Composer solution `.sln` file in Visual Studio
2) Right-click on `Dependencies` and click on `Manage NuGet Packages...`
     <img src="https://user-images.githubusercontent.com/38049078/166236654-793dc4f7-14e4-40ad-8173-f910ce0214c5.png" width="500"/>
3) In the `Installed` tab, select `Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime` package to `4.16.0` and click `Update`
     <img src="https://i.imgur.com/TfovYyI.png" width="500"/>

#

Let me know if you have any questions. Thanks.

**Comment by ryub3n** [comment]
Unfortunately I do not have Visual Studio but somehow managed to do it in VS Code using the [Nuget Package Manager GUI extension](https://marketplace.visualstudio.com/items?itemName=aliasadidev.nugetpackagemanagergui).

But isn't it a bug that the update isn't shown in Composer?
