### ISSUE TITLE
Core Bot with QnA Maker gives 404 not found

### ISSUE THREAD

**Issue by davhdavh** [microsoft/botframework-components#1324]
## Describe the bug
![image](https://user-images.githubusercontent.com/1201165/163089580-8ffa0254-9570-4464-9c3a-44afeb3a2a41.png)

## Version
2.1.2

## OS

- [ ] Windows

## To Reproduce

Brand new install

**Comment by ryanlengel** [comment]
This was my mistake, while we do not use the removed QnA template generator code [Composer is dependent on the README](https://github.com/microsoft/BotFramework-Composer/blob/01ccbcee840d5b8fe40fbde513956ad919f10317/Composer/packages/server/src/controllers/asset.ts#L127) that was provided. I will add the README back in and validate. Thanks for reporting @davhdavh!
