### ISSUE TITLE
Calendar Skill not displaying user name in the message when retrieving list of users

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1333]
## Describe the bug

Calendar Skill not displaying user name when retrieving list of users when creating an event

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
2. Create an event e.g. 'Set up a meeting for tomorrow at 9 AM'
3. Add a title
4. When it asks who it should invite give a name that has multiple entries e.g. John
5. It will return a list of entries for since it's not able to find a unique user
6. See the incorrect message 'I’ve found more than one ****:'

## Expected behavior

It should display the user name in the text 
e.g. 'I’ve found more than one **John**:'

## Screenshots

<img width="649" alt="image" src="https://user-images.githubusercontent.com/24279903/165468292-265c7589-f247-4651-bd1e-c8dd422b4d0d.png">

**Comment by ryub3n** [comment]
This 

https://github.com/microsoft/botframework-components/blob/29c1b124e005920abb4a8e8dc8db71a26780a784/generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/GetContactsDialog/GetContactsDialog.dialog#L434


Probably needs to be updated to 

```code
"contactName": "=titleCase($nameProperty)"
```

**Comment by ramfattah** [comment]
investigating.

**Comment by ramfattah** [comment]
Hi @ryub3n 

Update: I'm able to reproduce this issue.

Also, It seems after the card response, the error `Operation returned an invalid status code ‘BadRequest’` is thrown. https://github.com/microsoft/botframework-components/issues/1332

![image](https://user-images.githubusercontent.com/38049078/166076287-f122c87c-8fc6-4300-8173-248307a9e70b.png)

**Comment by ramfattah** [comment]
See also #1332
