### ISSUE TITLE
Calendar Skill - Old adaptive card buttons trigger junk response

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1338]
## Describe the bug

After sending a meeting invite if a user clicks on any of the invite summary adaptive card buttons a junk/error message is displayed.

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
3. Create an event e.g. 'Set up a meeting for tomorrow at 9 AM' and confirm it's been created.
5. After the bot replies that it's been created click on any of the card's buttons e.g. 'Add attendees', 'Update description', etc.
6. See error
## Expected behavior

Should not be clickable or should display appropriate error.

## Screenshots

<img width="558" alt="image" src="https://user-images.githubusercontent.com/24279903/169597171-0111ddb7-e128-4dac-908c-f27b77c221e1.png">

**Comment by ramfattah** [comment]
Hello @ryub3n, Thank you for your patience. We are investigating and will get back to you once we have updates.

**Comment by ramfattah** [comment]
Hi @ryub3n, thanks for reporting this issue.

I was able to reproduce using a fresh Composer Enterprise Assistant Template.

Composer v 2.1.2
Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime v 4.16.0

facing this issue after the meeting has been created and clicking on previous card buttons.

https://user-images.githubusercontent.com/38049078/171762197-048b72dc-fb80-40ab-a50a-d4c6a5a8c344.mp4

**Comment by ceciliaavila** [comment]
Fix available in linked PR (pending review).

**Comment by johnataylor** [comment]
we have a PR so marking this as exempt from the daily DRI report
