### ISSUE TITLE
Calendar Skill - Marking an event tentative throws an error to the user

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1340]
## Describe the bug

Marking an event as tentative is throwing an error message

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
2. Send "mark me as tentative for an event"
3. It'll ask for the event title. Enter an event name that you haven't responded to (preferably one that has a large audience e.g. an event from HR)
4. See error message

## Expected behavior

It should mark me tentative or give me an appropriate reply.

## Screenshots

<img width="328" alt="image" src="https://user-images.githubusercontent.com/24279903/169600066-ba8b8dc0-473b-4c1f-aa13-48c2e18dc159.png">

It also sends this which is not an appropriate message for the user.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/24279903/169600133-ed15980b-00b4-4485-873a-aca045bcfbc9.png">

**Comment by ramfattah** [comment]
investigating

**Comment by ramfattah** [comment]
Hello @ryub3n, Thank you for your patience. We are investigating and will get back to you once we have updates.

**Comment by ramfattah** [comment]
Hi @ryub3n, thanks for reporting this issue.

I was able to reproduce using a fresh Composer Enterprise Assistant Template, tho the error message is different from your screenshot.

Composer v 2.1.2
Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime v 4.16.0

#

Here are the steps I took:
1) Run [Enterprise Assistant Template](https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-overview) from local environment
2) Send `mark me as tentative for an event`
3) The bot will ask for the event title, example send `Weekly check-in with Engineers`
4) The following error is thrown
     <img src="https://user-images.githubusercontent.com/38049078/171777568-c57225ea-672d-4199-8bc6-ebf9cf1c9e05.png" width="600"/>


Error:
UpdateEventDialog.en-us.lg:formatDateTime has invalid first argument [FormatTimeRange] Error occurred when evaluating expression. [EventDateTimeContainer] Error occurred when evaluating expression. [EventDetailBody] Error occurred when evaluating expression. [EventDetailActionsCard] Error occurred when evaluating expression. [SendActivity_F6WlGO] Error occurred when evaluating expression. [__temp__87fcc1f83c8e421bb0f2fc06d561ee38] Error occurred when evaluating expression., UpdateEventDialog.en-us.lg:formatDateTime has invalid first argument [FormatTimeRange] Error occurred when evaluating expression. [EventDateTimeContainer] Error occurred when evaluating expression. [EventDetailBody] Error occurred when evaluating expression. [EventDetailActionsCard] Error occurred when evaluating expression. [SendActivity_F6WlGO] Error occurred when evaluating expression. [__temp__5db250b4bb734794a1862486fbc1e93d] Error occurred when evaluating expression.

**Comment by ryub3n** [comment]
@ramfattah, right that's the error you get if you're the meeting organizer, and if you're not you get a different error now similar to the one you sent. I don't know why it has changed but yes these errors need to be fixed.

**Comment by ceciliaavila** [comment]
We'll be tackling this one this week.

**Comment by johnataylor** [comment]
we have a PR so marking this as exempt from the daily DRI report
