### ISSUE TITLE
Microsoft.Bot.Components.Graph no longer works with latest version of Microsoft.Graph.Beta

### ISSUE THREAD

**Issue by davhdavh** [microsoft/botframework-components#1342]
## Describe the bug
Microsoft.Graph.Beta 5.4 results in this error on startup
`
Unhandled exception. System.AggregateException: Encountered exceptions while loading bot components. (Unable to load one or more of the requested types. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.IUserContactsCollectionPage' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.MeetingTimeSuggestionsResult' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.) ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.IUserContactsCollectionPage' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.MeetingTimeSuggestionsResult' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.Assembly.GetTypes() at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Component.AssemblyBotComponentEnumerator.GetComponents(String componentName)+MoveNext() at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Component.BotComponentDefinition.Load(IBotComponentEnumerator pluginEnumerator, IServiceCollection services, IConfiguration configuration) at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Extensions.ServiceCollectionExtensions.AddBotRuntimeComponents(IServiceCollection services, IConfiguration configuration) System.TypeLoadException: Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.WorkingHours' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.IUserContactsCollectionPage' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.ResponseType' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Event' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.MeetingTimeSuggestionsResult' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.DirectoryObject' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.User' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. System.TypeLoadException: Could not load type 'Microsoft.Graph.Person' from assembly 'Microsoft.Graph.Beta, Version=5.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. --- End of inner exception stack trace --- at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Extensions.ServiceCollectionExtensions.AddBotRuntimeComponents(IServiceCollection services, IConfiguration configuration) at Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Extensions.ServiceCollectionExtensions.AddBotRuntime(IServiceCollection services, IConfiguration configuration) at CatglobeBot.Startup.ConfigureServices(IServiceCollection services) in d:\src\catglobe-resources\integration\TeamsBot\CatglobeBot\Startup.cs:line 57 at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services) at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider() at Microsoft.Extensions.Hosting.HostBuilder.Build()`

## Version
1.3

**Comment by axelsrz** [comment]
Hello @davhdavh thanks for logging this, could you explain why you're using the Beta package for Microsoft.Graph?

**Comment by davhdavh** [comment]
https://github.com/microsoft/botframework-components/blob/main/packages/Graph/Microsoft.Bot.Components.Graph.csproj#L22

**Comment by anishprasad01** [comment]
Does the package work as expected in your bot with the pre-defined version of `"0.39.0-preview"`?

**Comment by davhdavh** [comment]
Yes. But I need to use other graph features not available in that function,
and it is not possible to use both the non beta version and the beta
version at the same time.

**Comment by anishprasad01** [comment]
At the moment, this version is not supported by `Bot.Components.Graph`. However, as a workaround, you could try the [instructions](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet#using-the-beta-client-along-with-the-v10-library) from the Graph Beta SDK repo on using both the beta and non-beta packages simultaneously.

**Comment by anishprasad01** [comment]
Since we have identified a workaround, I am going to go ahead and close this issue. If you need further help with this, feel free to comment and we can reopen the issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.
