### ISSUE TITLE
AdaptiveCards data property does not handle null values properly

### ISSUE THREAD

**Issue by davhdavh** [microsoft/botframework-components#1343]
## Describe the bug
![image](https://user-images.githubusercontent.com/1201165/170254035-0825d864-fab4-46a2-a60e-a306aecaa1a6.png)
if dialog.config.Site is null, the renderer behaves as if the given object has no .Site at all and just outputs "${$root.Site}".

Also, This defeats the purpose of coalesce function which REQUIRES the value to be null (to use 2nd arg), not just an empty string.

## Version
1.3

## To Reproduce
1. set a property in an object to null, e.g. dialog.Site = null
2. use object in data, i.e. =dialog
3a. use ${$root.Site} somewhere in adaptive card
3b. use ${coalesce($root.Site, "default")}

## Expected behavior
3a. rendered text is "", or "null", or "(null)". NOT "${$root.Site}"
3b. rendered text is "default"

**Comment by dmvtech** [comment]
Hello @davhdavh 

I'm confused on what `$root` is. Is that supposed to be a value in the template? i.e. are you using [Adaptive Card templating](https://docs.microsoft.com/en-us/adaptive-cards/templating/)? If so, that is currently not supported. Please see here for more information:
https://github.com/microsoft/botframework-sdk/issues/6477

If `root` is an object or property in memory scope, you must use the full 'path' to that using a supported memory scope. You cannot use your _own_ memory scope. For example if `root.Site` is supposed to be the same as `dialog.config.Site`, then you must use `$dialog.config.Site`. 

More info on memory scopes:
https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x#properties-and-memory-scopes

If I misunderstood the situation/scenario; please let me know and give more information that will help me understand. Thank you.
