### ISSUE TITLE
Calendar Skill - Unable to create or display events with a title having double quotes

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1350]
## Describe the bug

Unable to create or display events with a title having double quotes

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
2. Try creating an event with a title having double quotes e.g. "Testing"
3. See the error
4. You can also try creating an event using Outlook Calendar that has double quotes in the title but the bot will show an error when you try retrieving it.

## Expected behavior

Should not show errors even if the title has double quotes

**Comment by lauren-mills** [comment]
Hi @ryub3n, you can use the [replace()](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#replace) adaptive function to modify your project to support escape quotes in the title.
