### ISSUE TITLE
[NewTemplateRequest]

### ISSUE THREAD

**Issue by YamanAlbakri** [microsoft/botframework-components#1359]
i need a template , how is able to access sql database

**Comment by dmvtech** [comment]
Hi @yaman1612 

Thanks for your input and request. We will consider this for future templates. Please add any additional info or aspects you would like to see included.

In the meantime, you may be able to build something based off of this:
https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Storage.EntityFramework

This does not have any component registration for Composer, so you would need to implement that yourself.
