### ISSUE TITLE
[NewTemplateRequest]

### ISSUE THREAD

**Issue by Cyprien84** [microsoft/botframework-components#1363]
No templates pulled from currently configured template feed, please configure your feed to get templates.

Template Feed Url: https://registry.npmjs.org/-/v1/search?text=generator+keywords:bf-template+scope:microsoft

This feed did not return any templates, please confirm that this is a valid template feed URL.

**Comment by BruceHaley** [comment]
If I understand you correctly, the template feed URL is: https://registry.npmjs.org/

If that is not what you are looking for, please give me details on how to reproduce your problem.

Thanks.

**Comment by BruceHaley** [comment]
Closed due to inactivity. Feel free to reopen this issue if you are still having the problem.
