### ISSUE TITLE
InputHint 'ignoringSpeechInput' and 'ignoringNonSpeechInput' is not working

### ISSUE THREAD

**Issue by vinbala** [microsoft/botframework-components#1366]
## Bug
Bug: InputHint 'ignoringSpeechInput' and 'ignoringNonSpeechInput' is not working

## Version
Bot Framework Composer Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce
Has a speech prompt with InputHint = ignoringSpeechInput or InputHint = ignoringNonSpeechInput

## Expected behavior
InputHint = ignoringSpeechInput --> This should disable speech input, all other inputs should be allowed.
InputHint = ignoringNonSpeechInput --> This should disable all inputs other than speech.

## Screenshots
![image](https://user-images.githubusercontent.com/38055987/187298980-edf0aa0f-3576-4be3-90b7-fa3a16bd40bd.png)

**Comment by jameslew** [comment]
Note - this is in the Telephony composer package. Per docs barge in docs we should be able to override composer setting by specifying a valid inputHint inside the prompt.

The doc reference two additional inputHint values: https://github.com/microsoft/botframework-telephony/blob/28ff59a78c5678b731b795d5bb4e54e9ac933f1b/BargeIn.md#inputhint-additions

I can only find the base three however in the inputHints.cs schema: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/InputHints.cs

**Comment by ramfattah** [comment]
The [InputHints ](https://github.com/microsoft/botbuilder-js/blob/a79ddf9156e10418b8cb528216764784b6aa082c/libraries/botframework-schema/src/index.ts#L2127) field in JavaScript SDK side contains the same three constants as the .NET SDK:

#### JavaScript SDK 
https://github.com/microsoft/botbuilder-js/blob/a79ddf9156e10418b8cb528216764784b6aa082c/libraries/botframework-schema/src/index.ts#L2127
```js
export enum InputHints {
    AcceptingInput = 'acceptingInput',
    IgnoringInput = 'ignoringInput',
    ExpectingInput = 'expectingInput',
}
```

#### .NET SDK
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/InputHints.cs
```cs
    public static class InputHints
    {
        /// <summary>
        /// The hint value for accepting input.
        /// </summary>
        public const string AcceptingInput = "acceptingInput";

        /// <summary>
        /// The hint value for ignoring input.
        /// </summary>
        public const string IgnoringInput = "ignoringInput";

        /// <summary>
        /// The hint value for expecting input.
        /// </summary>
        public const string ExpectingInput = "expectingInput";
    }
```

**Comment by johnataylor** [comment]
@vinbala thanks for opening this issue, however, we are not prioritizing this work at this stage, closing.

**Comment by stevengum** [comment]
The ignoringSpeechInput and ignoringNonSpeechInput InputHints do work, however they only apply for the duration of the message playback.

See the newly added FAQ's question: [What are `<break>` tags? Why are `<break>` tags useful?](https://github.com/microsoft/botframework-components/blob/stgum/faq/packages/Telephony/FAQ.md#what-are-break-tags-why-are-break-tags-useful) for an example on how to combine `<break>` tags with InputHints to achieve the desired result of only accepting DTMF or Speech Inputs
