### ISSUE TITLE
'Timeout in milliseconds' property not working in 'Multi choice with silence detection | Preview' action.

### ISSUE THREAD

**Issue by vinbala** [microsoft/botframework-components#1367]
## Describe the bug
Bug - 'Timeout in milliseconds' property not working in 'Multi choice with silence detection | Preview' action.

## Version
Bot Framework Composer Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce
1. Create a new project.
2. Install 'Microsoft.Bot.Components.Telephony' Package via Package Manager.
3. Configure a step 'Multi choice with silence detection | Preview'.
4. Enter 'Timeout in milliseconds' property value with value 10000.
5. Valiate if the bot is timing out, i.e. After the specified amount of milliseconds, the dialog will complete with its default value if the user doesn't respond.

## Expected behavior
After the specified amount of milliseconds the dialog will complete with its default value if the user doesn't respond.

## Screenshots
![image](https://user-images.githubusercontent.com/38055987/187305766-0b0487a0-e5df-4bd3-ba48-a039603e9cca.png)

**Comment by ramfattah** [comment]
Thanks @vinbala, we are investigating this issue.

**Comment by ramfattah** [comment]
The team is currently discussing about this internally. Thanks for your patience, @vinbala

**Comment by johnataylor** [comment]
@vinbala thanks for opening this issue. However, this work is not being prioritized at this time.
