### ISSUE TITLE
Enterprise People Bot list not working in Teams

### ISSUE THREAD

**Issue by nickfrancis** [microsoft/botframework-components#1379]
## Describe the bug

I'm aware there is a similar issue but mine appears to be slightly different....

When using my Bot in Teams, if there are multiple matches it throws an error:
![image](https://user-images.githubusercontent.com/115018551/199733689-f83a9b48-d1a1-494d-9d1f-69cb0ff16941.png)

Same feature works absolutely fine in Emulator / WebChat
![image](https://user-images.githubusercontent.com/115018551/199733995-af5c93aa-0693-4804-9935-d5b373ebb951.png)

If I look in Azure all I see is this:
![image](https://user-images.githubusercontent.com/115018551/199734128-459ecf13-001b-479e-8895-7fb550a084a3.png)

I've tried to hunt through Azure analytics to see if I can narrow down the error but can't find anything.

I've checked the cards file & can see it's using Adaptive Cards, not List Cards so it's not that.

Any input welcome :)

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by ramfattah** [comment]
Thanks @nickfrancis, we are investigating.

**Comment by nickfrancis** [comment]
To add to this - had a look in Azure insight and found the error exception that was being returned.

![image](https://user-images.githubusercontent.com/2065211/201082744-97508f2c-316f-4f42-8620-0bb5fa7d701f.png)



Doesn't appear to be showing me much information, as the code cuts off midway through a bas64 png url. Not sure if that is the problem?

Code attached - have removed app id references etc
`{
  "Request": {
    "Method": {
      "Method": "POST"
    },
    "RequestUri": "https://smba.trafficmanager.net/amer/v3/conversations/********QAWgW0j5DW-N6s0gPeyAhRbyNi72Kv_CeB98i2eCRAwxgd6O6AXhvc3mtaSw4rGNddZAL/activities/1668078961754",
    "Properties": {},
    "Content": "{\"type\":\"message\",\"serviceUrl\":\"https://smba.trafficmanager.net/amer/\",\"channelId\":\"msteams\",\"from\":{\"id\":\"********\",\"name\":\"CPM IT Chatbot\"},\"conversation\":{\"conversationType\":\"personal\",\"id\":\"a:********\",\"tenantId\":\"*******-*\"},\"recipient\":{\"id\":\"********\",\"name\":\"********\",\"aadObjectId\":\"*********\",\"role\":\"user\"},\"locale\":\"en-US\",\"text\":\"I found multiple matches for **Andy**. Please pick one:\",\"speak\":\"I found multiple matches for **Andy**. Please pick one:\",\"inputHint\":\"expectingInput\",\"attachments\":[{\"contentType\":\"application/vnd.microsoft.card.adaptive\",\"content\":{\"type\":\"AdaptiveCard\",\"$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\",\"version\":\"1.2\",\"body\":[{\"type\":\"Container\",\"items\":[{\"type\":\"ColumnSet\",\"spacing\":\"none\",\"columns\":[{\"type\":\"Column\",\"width\":5,\"verticalContentAlignment\":\"Top\",\"items\":[{\"type\":\"Image\",\"url\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAALEgAACxIB0t1+/AAABIBJREFUeF7tnO1t2zAQhj1CN2hHyAgZoSMokgwE6I9mg2SDdIMEKGz5T5Fu0BEyQkbwCOkdefkwfaS+KIqy3wc4NAhFSjiKd0fqTVcAAAAAAAAAAAAA81HUvy/Lendf1bvnst7uy7p5tbbdV3Xzj9uKavtdLgdTUBQPX8jpt4cT0GLr5qVa735yXxkGxKCit73XRLhGE1OWm0KGA2Pg8KM6eZjdyrBgCGXVPChOHWc0pgwP+kDOo3yhOFSMcsMTJ+7iuvkmXVbFenPBv7uqto9anw/b3UsX0AWO97ojaSKoiiqKj0nwwdeEJgZVWEfYkSYJK04ku5PLOsN9nDHEdntUXx0gZ/lCVe/JeIP7OmOJbQaPeTaoqyNCIr4yG0ZnXFol0gw07H7DdRrF+w45ow0TCrWx6+ZSLgEuapkbsUzVVgkl/l/SDFzsOdShw3jVSPNotOqNz8OkGbhoxyPVjz9fpXk0ethCHvFy7KzmVZqikeIeJ0MKZ6W4x8kwfcjaXLjjI2QFqOrts+uwmEldK6u5kJBm4MIlqOuwmGWpVlaj7A3AmzTXYfbMabqNYcwVeHLYz7TKl8H17kkuGYxn0/kizcAHH/gdOc7Y9kYu6Q31j35geTZ4V4m13p9guY8zhjVaHTFC4VlQltsb1YlsFHq6ONLkjGr3pI7BVjYQPfRBq7gOjCeGEnJx/fA+Ofwz/44/7wZWGSqroZDjWr6N97erqnmU4cEQWldKD8PKGIlJ8Fq5OtQ65h+gwBLQUB4YbFAx9od25zHVij47PRVjbBU6hyjtq6Fr5hoqjY0w7pOUh382xy/UZistvf+7UQiTrsvFbtz6q9Dp39u2+B2cjMrc7+7zBLTB97NFQeBZlzwp9vh6RFwPxO9gmKINXp+JcJGJCZTQC5SWxo3rhw4ISUfpBRh8huVC43nOyRYmLY1aer6ZhApzxOGTjq7jH28UZeOZ/IVIS+lhJ1WhByZ7spNY/1lZ5qErhQpdtQSJlr+xaPfOdpUEQ8mAt5f7OGPoluhY3FaLWoGSqQCbHi6hCv3AkjlE/xiWqQpFXR0RQomuQv+wFKvjDbtKlGfITYCtyWXMg0ZwlgmFythsNFl/5bJk6C9IvFI7CmrlEzHRelfJDF/x2Pnuc8zxYgTRjjBiymV81dscoUJVM1K4luY80KqP6VXo85Sceh7JLLEfP+Bpi55zehaVFA+Y4h4nw/QhCyr0XkCFnhn2o86hw/h30jwarayOOf7JARV6ZngP3qBCnw+o0DPDfzxtDCr0OYAKPUO0iuvAeGIoIUOFnhByHFToudG6UnoYVsZITILXytWh1jH/AAWo0DOCdUqqM+Ma/i/dNjhEBYXPYuYaqNCnJ7hvgAo9LcEwBRV6WqBCzwhzxAEVej4E9hmTncQuVoU+NWZ1aI5JkGgXp0JPgbo6oEKfD0/ugAp9DuyfNrvOiCOs7opdJcoz5KZCT4H2dkKFPiPqrhwq9PnQRHFQoc+IVuHMUXLqeeQME/uxE6BCBwAAAAAAAAAAAAAAAABAZqxW/wGFvEhJhswaMQAAAABJRU5ErkJggg==\",\"horizontalAlignment\":\"Center\",\"width\":\"18px\",\"height\":\"18px\"}]},{\"type\":\"Column\",\"width\":65,\"verticalContentAlignment\":\"Top\",\"items\":[{\"type\":\"TextBlock\",\"text\":\"Colleagues\",\"size\":\"Medium\",\"weight\":\"Bolder\"}]},{\"type\":\"Column\",\"width\":30,\"verticalContentAlignment\":\"Bottom\",\"items\":[{\"type\":\"TextBlock\",\"text\":\"8 results\",\"size\":\"Small\",\"horizontalAlignment\":\"Right\"}]}]}]},{\"type\":\"Container\",\"separator\":true,\"spacing\":\"medium\",\"items\":[{\"type\":\"Container\",\"separator\":true,\"spacing\":\"Small\",\"selectAction\":{\"type\":\"Action.Submit\",\"title\":\"selectOption\",\"data\":{\"skillId\":\"EnterprisePeople\",\"value\":\"1\",\"msteams\":{\"type\":\"messageBack\",\"value\":\"1\",\"text\":\"andy\"}}},\"items\":[{\"type\":\"ColumnSet\",\"spacing\":\"Small\",\"columns\":[{\"type\":\"Column\",\"width\":10,\"items\":[{\"type\":\"Image\",\"url\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAYAAAByDd+UAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAALEgAACxIB0t1+/AAAAfRJREFUSEu9VrFOwzAQzafwKf0E/qCJ7XZCjMBWGBEDSIgRFoQTJIbSBURASAgkpnboQFhggIWpnxD8nKQk8SV1opaT3nJ39su93Nl2bMwV5x0mgkMuggkTcsaEHyeQMy78R8SQk6a3N8YuXNbzP/8IFgC5ak263N5c11/jPVRDbGoDRYw90u3qjfdltyhbWwQzl8v1dFvauEqgF7eH17/sptsXDRIsp7IyVKWUvI2aoyE81d0pTWK6G4nEpSLfvbbVbW2P4ij60XhTeH75iLd2RmSuAcWhyZKhJhJKyMgGe7eGb2PzqpBbBVf4Hcfj8ogKlnEXRvHxyZPh3z94iIfXU8NPAVxOcjTRCXmgEsoPQF7KXwaORsd2FMaTL1I6yDoefxt+GsFMEVIBE5AuDN8Nf6ikPj17NfxVsCYEhqOp7kyQ43+iMvio3CpYSwo5QQaS8D7SjdJ4NCApF3LhrZC1PyorxzAmtqOBBrUai0xGKgYghhwqloceCwwjFcyAL7dpe5sq9eDDGK8+2vD1NoONg2Gwe0PGNBSHJoMx5v/D4e0Xnx6eRfO0Rr66zFZ2AXNJX8AwdwXS4tmSbk8bHj5LqVRVpu5AuyejlremcxcBt0KljHWmu7cJMXLL3djGMLA4JfTdCanmBHjqywli86GuNcf5BRpNKUEndoEwAAAAAElFTkSuQmCC\",\"style\":\"Person\",\"size\":\"14px\"}]},{\"type\":\"Column\",\"width\":90,\"items\":[{\"type\":\"TextBlock\",\"text\":\"andy\",\"wrap\":true,\"weight\":\"Bolder\"},{\"type\":\"TextBlock\",\"text\":\"\",\"wrap\":true,\"spacing\":\"None\"}]}]}]},{\"type\":\"Container\",\"separator\":true,\"spacing\":\"Small\",\"selectAction\":{\"type\":\"Action.Submit\",\"title\":\"selectOption\",\"data\":{\"skillId\":\"EnterprisePeople\",\"value\":\"2\",\"msteams\":{\"type\":\"messageBack\",\"value\":\"2\",\"text\":\"Andy Aird-Bombo (HCG)\"}}},\"items\":[{\"type\":\"ColumnSet\",\"spacing\":\"Small\",\"columns\":[{\"type\":\"Column\",\"width\":10,\"items\":[{\"type\":\"Image\",\"url\":\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAGkAaQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0Y9fwooPX8KKk0F70vemiloAWikzS0AFFFFMA70tJRQAtFFFABS0lL3oEFLRRQIKSlooASilo7UAJSGlpKAQlFLSGgYUlFFOwBSc0UUwEpKd7UUDExmkp3akqQEpuKdSGgBtJTu9JQA00hp1NNACUh69KWikwG/hSdqdTaQCdKTFLRQAyk6U+m44NIBpHFRkVIelNPb3oAYeKYe9PIOKaQKAGNTGFSN7CmNQA1u30opSM4NFOwG8f6UlFFMB1FJRQAtGaSl60AFLSUUwHCikpaAFopKWgBaKSloEFLSUUxMKKKKACg0d6KQCGkpTRTGhKKKKYCUUtFAhKKWigBtFLRzQMSk6UvekNIBKSnUlIY3vSUp4pKAEopaTFADTSYpxppqQEPTpSU6kNADaSlooAbSU6mmkA00006kIoAjP9aaafSHg0ARH1pp5p5FIeOKAIz257UUpFFMRud6KD1/CkpjFopKWmAUtJRQAtLSUtAC0UUUALRRRQAtFFFAC0lFJTQh1JSUtMGHNHaiigSEopaSgYUvFIKXigGJRRRQIKSlooGJRRRQMKSlooATFNp1JUgNNJS9KKAG0GikoAKbinUhpMBtJTqTFIBMU09Kcab1oAQ9KbTjSfhQAw/Wkpx602kA04/Om9+lPNN9T2oAYfSmHpxTyKafpmgBpU4GD2oo6gUUwNk9fwpKU0VQBS0lLQAUUUUALS0lLQAtHNFLQK4Uc0lLQCClpKO1AMKKKKoELRSUUAFLR2ooASil70lAxaKKKBB2pKKKACiijvQAUUUUDEo7UtJQAUhpaQ1ICGmkcU40mOKAG0UUUAJSEcUtFJgNxSU6kpANpMU6k70ANxTTTjjFNxQA09ab1p5ppFIBp6038KdTSKAGHrTD0NPNNIoAaeg+lFGOlFMDYP9KKU0VQBRRRQAUUtFABS0UUCFooooAKM0UlNAOopKWmDDtRRRQJBR2pfSigYUUd6KACiiloGJRS0lABRRS0AJRS0mKACiloxQIbiilpKBhSUtGKTAbSUtJSAQ0mKWigBtFFFJgJSU6kpANNNxT8U3BpgNIpDT8U09OKQDDTacaTGaAGdutNNPppHekAw0wipDnNNNAEZFFOPaimI1z/Skpx/pSVQwoopaADFGKKKBBS0UtACd6KXFFOwriUYpaKYwopaKAD60UUtAgooooBCUUtFAwpCQBknGKZLcQwrmSVF+rV5X49+IF9Z3smm6ayJGF+eQjLH6UroZ2+peNtD0rUBZ3N1tfblmAyq/U0238d+GrkyCPVYcpywbjivnebUZ72dp7iQyO33mbqaqsxG7C/eFAHu/iT4oaXptgJNKngvZ3O1QGOF9zXOQ/GK+jUtc2ELnPAjJA/WvKP9kHkDI9BT97MODnFS7iuesXnxmbbbva2IUsD50ch4U+xrt/CvjG08TRN5aPFMgBdG5xn3r5uPzLg8HrmtHRtd1LR5ZH0+8e3crjKgHd+dNAfU1FeHQfGDWobWCN7aGWVeJJH/AIvyrrrL4u6PNHCLqGaKRgN+BkKelO4HodIaSORJolkQgqwyKWmAlFFHekxiUhp1NNIBKKKKAExRj6UuO`

**Comment by nickfrancis** [comment]
Any news @ramfattah?

**Comment by ramfattah** [comment]
Hi @nickfrancis, 

As QnA service is deprecated, I'm not able to run the [Enterprise Assistant Bot](https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-enterprise-assistant) from my local machine.
![image](https://user-images.githubusercontent.com/38049078/202313897-d30deb30-bc0e-48f5-b1b9-d3f5421e535f.png)


Discussing this internally for the next steps.
Thanks for your patience.

**Comment by nickfrancis** [comment]
Hi @ramfattah 
Any news?

**Comment by nickfrancis** [comment]
Further update - found a slightly more helpful error:
![image](https://user-images.githubusercontent.com/2065211/207663119-2681fe54-5268-4d36-82ea-350ca6d1096b.png)

Clearly something wrong with the Adaptive Card being used to display a list of users.

**Comment by nickfrancis** [comment]
@ramfattah this issue can now be closed. Did further digging and found that in the Adaptive Card the icon size was calling a px variable:

```
"items": [
                        {
                            "type": "Image",
                            "url": "${ContactImageIconUrl(item.Photo)}",
                            "style": "Person",
                            "size": "14px",
                        }
                    ]
```

This isn't a valid Adaptive Card variable and even though Emulator was working with it, Teams couldn't handle it. Replaced it with the following:

```
"items": [
                        {
                            "type": "Image",
                            "url": "${ContactImageIconUrl(item.Photo)}",
                            "style": "Person",
                            "size": "Small",
                        }
                    ]
```

Teams now able to render the adaptive card properly:
![image](https://user-images.githubusercontent.com/2065211/208715723-252818f8-a488-43cb-932b-974efdf8ca82.png)

Issue closed

**Comment by ramfattah** [comment]
Hey thanks @nickfrancis for sharing your knowledge. Much appreciated :)
