### ISSUE TITLE
[Telephony] Aggregate DTMF Inputs (n) doesn't stop at specific length

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-components#1404]
## Describe the bug

When using the aggregate DTMF input node, and a batch length of ten.
The user provides `90` as the first input, which is aggregated as expected.
The user then provides `1234567890` which is also aggregated.
The end aggregation is `901234567890`, which has a length of 12, greater than the batch length.

### Additional context
The node does stop when the inputs are singular, e.g., ten single-digit numbers are provided and the batch length is ten. The issue looks to be around the length of the latest aggregated value if the latest input is valid.

## Version

`latest` 

## To Reproduce

See _Describe the bug_ section.

## Expected behavior

The node should clarify the input and/or offer the ability to start over after informing the end user of the current aggregation/why it's offering the ability to restart.

**Comment by ceciliaavila** [comment]
Hi @stevengum,
We reviewed this issue and the code of the [aggregate DTMF input](https://github.com/microsoft/botframework-components/blob/main/packages/Telephony/Actions/BatchFixedLengthInput.cs#L45) and found that the batch length is defined as the minimum amount of characters collected before storing the value and ending the dialog. It's not a limit for the user's input.
Do you still consider we should add a restart ability?
