### ISSUE TITLE
Cannot publish bot with new Custom Question Answering Recognizer component using Bot Composer

### ISSUE THREAD

**Issue by Alwinator** [microsoft/botframework-components#1430]
## Describe the bug
I have set up a bot with the new Custom Question Answering Recognizer component. However, when I try to publish it using the Bot Composer I get an error. The bot works fine in the compose and the emulator.  See logs below.

## Version
v2.1.2

## To Reproduce
1. Follow the setup guide [here](https://github.com/microsoft/botframework-components/blob/main/packages/Recognizers/CustomQuestionAnswering/README.md)
2. Publish to azure (auto-create resources)

## Expected behavior
Bot gets deployed to azure

## Screenshots

![image](https://user-images.githubusercontent.com/39517491/207883811-3d5a7fd8-0026-4e20-beb3-d6fbd90da8f8.png)

## Additional context

```
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: az-euw-dev-rg-testbot at westeurope",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed after 3 retries. Error: Request failed with status code 403",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}. See provision. TestBot.log in your bot folder"
```

**Comment by anishprasad01** [comment]
Hi @Alwinator,

I gave it a quick try and I am unable to reproduce your issue. I created a new bot in Composer, followed the README to enable CQA, and then published the bot to Azure from Composer. I was able to communicate with the bot in the Test Web Chat in the Azure portal.

A couple of things to clarify:

- Is your Composer publishing profile attempting to provision and/or deploy a QnA resource to Azure? It is expected that this will not work as the ability to create QnA resources has been turned off.
- What resources exactly are you attempting to deploy?
- You appear to be experiencing a 403 Forbidden error when creating the App Registration itself (before we even get to deployment). Has there been any change to your permissions? 
- Does the logfile the error message references (`See provision. TestBot.log in your bot folder`) have more detailed messaging? Perhaps a more detailed error trace?

**Comment by Alwinator** [comment]
> Is your Composer publishing profile attempting to provision and/or deploy a QnA resource to Azure? It is expected that this will not work as the ability to create QnA resources has been turned off.

Yes, I think so. I was assuming that the BotComposer deploys all the services I need for my project. However, it looks like it is deploying the old, wrong ones, but correct me if I am wrong.

> What resources exactly are you attempting to deploy?

![InkedInkedScreenshot 2022-12-19 084228](https://user-images.githubusercontent.com/39517491/208428979-e7da24c1-25d2-4678-a29e-416f555a51b2.jpg)

![InkedScreenshot 2022-12-19 084247](https://user-images.githubusercontent.com/39517491/208429002-a98738ef-9067-48f2-a2d4-6390600ecfd4.jpg)

> You appear to be experiencing a 403 Forbidden error when creating the App Registration itself (before we even get to deployment). Has there been any change to your permissions?

I will check this with my companies Azure team, but that can take some time, because of Christmas.

> Does the logfile the error message references (See provision. TestBot.log in your bot folder) have more detailed messaging? Perhaps a more detailed error trace?

The log file contains exactly the logs I mentioned in the Additional context of my issue and the project name and time. However, due to internal guidelines I cannot publish the project name.

Is the automatic deployment (with the new language model) officially supported in BotComposer?

**Comment by anishprasad01** [comment]
> Is the automatic deployment (with the new language model) officially supported in BotComposer?

No. In order to get this to work, you need to deploy the new Azure Language separately in the Azure Portal. 

Once you've done that that, you can configure the recognizer and deploy the bot. Make sure to *uncheck* "Microsoft QnA Maker" in your publishing profile, as that will cause provisioning to fail. I'm thinking that perhaps the 403 error might be for QnA.

Please retry without deploying QnA Maker to see if that works.

**Comment by Alwinator** [comment]
Good to know! With existing resources, I was able to deploy the chatbot successfully! Thank you very much for your support! ;)
