### ISSUE TITLE
[NewTemplateRequest] Templates for the current .NET version. Core 3.1 is no longer supported

### ISSUE THREAD

**Issue by NSouth** [microsoft/botframework-components#1493]
I was surprised to find that the templates use Core 3.1 which is out of support. Please update templates to use an LTS version of .NET (currently .NET 6) or provide instructions for upgrading. Thank you.

**Comment by anishprasad01** [comment]
Hi @NSouth,

Updating the templates to .NET 6.0 is currently in progress and should be available in the near feature. In the meantime, you can of course go into your `.csproj` file and change the target framework manually.
