### ISSUE TITLE
Bot publishing error

### ISSUE THREAD

**Issue by Francesco-dotcom** [microsoft/botframework-components#1497]
## Describe the bug

I created a Custom question answering project on language studio.
I used the bot framework composer to create an empty bot and installed the package: 
"Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer".

![image](https://user-images.githubusercontent.com/112615341/236162090-47da7bc4-b510-4021-b11c-2edbd1e40df7.png)

I created the dialog on composer and configured the json in the custom recognizer type window.
like this:
{
 "$kind": "Microsoft.CustomQuestionAnsweringRecognizer",
  "hostname":"<your endpoint, including https://>",
  "projectName": "<project name>",
  "endpointKey": "<your endpoint key>"
}
 now testing the bot the conversation proceeds smoothly by interacting with the knowledge base on the language resource.

I want to publish the bot to Teams, so I created the publishing profile and associated the bot with the corresponding resource on Azure.
Trying to publish the bot I get this error:

![image](https://user-images.githubusercontent.com/112615341/236157148-cca968e8-6cad-4711-8b97-89be1d1e373a.png)

The requested resource cannot be created because:

![image](https://user-images.githubusercontent.com/112615341/236157298-9737314f-379c-492b-992c-2bbb38e46f8b.png)

I would need help to solve the problem.
Thanks.

## Version

![image](https://user-images.githubusercontent.com/112615341/236160998-6357c546-4f5b-4c65-9fa4-ab8690d5b2fe.png)

## Expected behavior

Is it possible to run a bot publication without the need to provision a language understanding resource?

**Comment by ramfattah** [comment]
Thanks @Francesco-dotcom, I'm investigating this issue.

**Comment by anishprasad01** [comment]
Hi @Francesco-dotcom,

As of April 1, 2023, it is no longer possible to provision new LUIS resources.

In order to publish a bot to Azure from Composer without LUIS, please first ensure that there are no recognizers or dialogs in your bot that use language understanding. Once you're done this, you should be able to uncheck LUIS in your publishing profile and provision the Azure resources. Also ensure that QnA Maker is unchecked in the publishing profile.

**Comment by davidcg96** [comment]
hi, i have the same error but i have probe to uncheck LUIS and QnA and the bot dont work well. when i ask a question of the CQA that i have implemented dont work.

**Comment by anishprasad01** [comment]
@davidcg96 

What isn't working, exactly?

**Comment by anishprasad01** [comment]
I just tested this again to confirm, but installing the CQA Recognizer package does not automatically create new QnA dialogs. Setting up the CQA package is a manual process. What bot template did you start with?

**Comment by davidcg96** [comment]
i have a question, with Luis if you go to one dialog and crear a intent trigger you can put words for trigguer the dialog. Like help and cancel example in weahther bot. But if you use CLU, you have put recognizer language to custom and now if you try use intent tigguer for reply wheaterBot you cant put this words. How can i cancel the dialog?
