### ISSUE TITLE
Problem installing packages

### ISSUE THREAD

**Issue by davidcg96** [microsoft/botframework-components#1505]
rror occurred building the bot

 

I install new packages in my bot and now dont work. when i tested appear this message.
How can i fix this?

Message:

Command failed: dotnet build Bot.csproj

Command:

dotnet build TireaBot.csproj

Stack Trace:

Error: Command failed: dotnet build TBot.csproj

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

warning NU1701: El paquete "Microsoft.Azure.KeyVault.Core 1.0.0" se restaur� con ".NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8" en lugar de la plataforma de destino del proyecto ".NETCoreApp,Version=v3.1".

**Comment by rvinothrajendran** [comment]
open this project in the visual studio and try again
