### ISSUE TITLE
Malfunctioning issue:  CLU custom recognizer in Composer

### ISSUE THREAD

**Issue by srinath555** [microsoft/botframework-components#1510]
Hi Team, 

I'm working on Composer bot to integrate with CLU as custom Recognizer, So I've added CLU as a custom recognizer to Bot Framework Composer Bot referencing this doc (https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding/dotnet).

The CLU project is trained 2 intents called “MainMenu” and “Cancel” in English, Spanish and French and when tested in CLU Language Studio Portal the Score range is between 0-1 (ex. 0.58299) for any utterance. 
![image](https://github.com/microsoft/BotFramework-Composer/assets/26254940/2369676b-f2f8-46da-8b6f-ba988a787314)

But when executed composer dialogs and user language is set to “ Spanish” or “French” for any utterance the recognizer should return the score in range of 0-1 but it is returning score like **58299387.0** instead of **0.58299387**. 

Below are example we tried for the utterance  “end my flow“ in English and “terminar mi flujo” in Spanish.
![image](https://github.com/microsoft/BotFramework-Composer/assets/26254940/8c8e9c7c-8044-487c-b612-e10bd340787d)

**Apart from English for all languages I'm facing this issue**, only for English it is returning the score between 0 – 1 which is as expected.
![image](https://github.com/microsoft/BotFramework-Composer/assets/26254940/c51d721f-3072-43dc-b832-3b0f25dafa02)

Please help me to get it resolved, Thanks in advance!

**Comment by anishprasad01** [comment]
@srinath555,

I believe this to be caused by an error in parsing the confidence score in the SDK due to the different ways that fractional values are represented in different cultures. I've opened a PR to fix this, pending sufficient testing and verification.
