### ISSUE TITLE
FoodOrdering/CinemasBookTicket/TicketOrdering/vehiceRent

### ISSUE THREAD

**Issue by FaiyyRozz** [microsoft/botframework-components#1512]
Hello, first of all I'm new here. I look out some help or resource that can guide me. So here I need to understanding the flow of of chatbot. that is why I request this template. I hope someone out there can help me. this is my first and beginner career and I have zero knowledge about AI. Thank you.

**Comment by anishprasad01** [comment]
Hi @FaiyyRozz,

I would suggest starting with the [Bot Framework Documentation](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0) to get an idea of how these bots work. In conjunction with the docs, you can peruse the [Samples repo](https://github.com/microsoft/BotBuilder-Samples) to view and download bot samples covering a variety of use cases in different languages.

Lastly, if you wish to use C# code to write a bot and are using Visual Studio on Windows, you can download and install the [Bot Builder v4 Templates VSIX package](https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4) to add a series of basic bot templates to your VS installation.

**Comment by FaiyyRozz** [comment]
Thank you @anishprasad01. 

> Hi @FaiyyRozz,
> 
> I would suggest starting with the [Bot Framework Documentation](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0) to get an idea of how these bots work. In conjunction with the docs, you can peruse the [Samples repo](https://github.com/microsoft/BotBuilder-Samples) to view and download bot samples covering a variety of use cases in different languages.
> 
> Lastly, if you wish to use C# code to write a bot and are using Visual Studio on Windows, you can download and install the [Bot Builder v4 Templates VSIX package](https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4) to add a series of basic bot templates to your VS installation. Otherwise, you can download an empty bot sample and use it as a starting point.

**Comment by FaiyyRozz** [comment]
Thank you @anishprasad01 for the help. I will try my best.
