### ISSUE TITLE
BUG with upload a file

### ISSUE THREAD

**Issue by davidcg96** [microsoft/botframework-components#1520]
Hi.

I want to upload a anything file in framework composer but this dont work.
For example, this is my idea:

I want to the bot say: please, can you upload the file whit the sign?
and the user: select clip icon on the bot and select all files that need to upload.

There are a bug when i do this.

![image](https://github.com/microsoft/botframework-components/assets/49916234/c26cdb91-70de-46c0-87e6-0868ba54b73e)

Dont recognize the acction and if then you upload a file. The intent is i dont know

![image](https://github.com/microsoft/botframework-components/assets/49916234/14b8fa57-f767-47c9-ac36-74d7501c8050)

How can i upload anything file, in my case a pdf file like this:
I want to the bot say: please, can you upload the file whit the sign?
and the user: select clip icon on the bot and select all files that need to upload.

**Comment by dmvtech** [comment]
@davidcg96 

Can you move your prompt for attachment outside of the welcome dialog into it's own dialog, and then call that dialog from the welcome? (This is a better design/idea in general). Let me know if the issue persists once you do that.

**Comment by dmvtech** [comment]
Closing due to lack of response.
