### ISSUE TITLE
Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer

### ISSUE THREAD

**Issue by jimmygohhanjie** [microsoft/botframework-components#1544]
i am a student using bot composer in VM. when i tried to install the package 1.0.0, it encounter error.

A problem occured during the install of this Component: Error certificate has expired *** Could not merge components ***

how to resolve this error?

**Comment by dixanthomass** [comment]
having the same issue while trying to install this package in bot framework composer!

**Comment by dmvtech** [comment]
Duplicate of https://github.com/microsoft/BotFramework-Composer/issues/9662
