### ISSUE TITLE
Microsoft.Bot.Components.HelpAndCancel Latest: 1.4.0

### ISSUE THREAD

**Issue by gersepa** [microsoft/botframework-components#1549]
## Describe the bug

A problem occurred during the install of this Component: Error certificate has expired *** Could not merge components ***

## Version

component 1.4.0 SDK 2.1.2

**Comment by dmvtech** [comment]
Does following the steps here resolve the issue?:
https://github.com/microsoft/BotFramework-Composer/issues/9690

**Comment by gersepa** [comment]
Hi Dana,

Thank you very much for your interest in my issue. Unfortunately, I am not sure how to check the SDK version. What I did, based on an article found in Github, was to download the night build for bot frame composer (v2.13-nightly.364675.1a93f21) and that fixed my issue so I was able to install several packages including the one I was having issues with.

On the other hand, it is so frustrating but due to the fact that this is a complex software there are a lot of things that do not work as specified in the documentation. Looks like the documentation is not upddated accordingly to new developments or updates to the product. So frustrating...

Now I am stuck trying to publish my bot to Azure.

Cheers,
German
________________________________

**Comment by gersepa** [comment]
Hi Dana,

Not sure if all my troubles are related to bot framework sdk or not. Could you please send me a link for the latest release of the afore-mentioned software?
________________________________
