### ISSUE TITLE
[NewTemplateRequest]

### ISSUE THREAD

**Issue by dabonai** [microsoft/botframework-components#1558]
Hi, can you create a template to connect to Azure OpenAI asisstant?

Regards,
danny

**Comment by tracyboehrer** [comment]
@dabonai This would require a Custom Action to be written.  It would just appear as a new action in Composer.  However, we don't have any plans to add AI related functionality to Composer.

See https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/packages/MultiplyDialog
