### ISSUE TITLE
[NewTemplateRequest] Python Templates for Bot Composer

### ISSUE THREAD

**Issue by LZGST** [microsoft/botframework-components#1565]
As a student, I would like to have Python Templates in Bot Composer for easy bot development. In University, we mostly learn Java & Python and would be very helpful to have Python Templates to use my knowledge.

**Comment by tracyboehrer** [comment]
@LZGST Python does not have support for Adaptive Dialogs, which Composer requires.  We don't have any plans to bring Composer support to Python though.
