### ISSUE TITLE
Email Skill not working as expected.

### ISSUE THREAD

**Issue by parasdesaicims** [microsoft/botframework-components#322]
**What project is affected?**

1.  Email skill

**What language is this in?**

English

**What happens?**

Email skill doesn't work.

**What were you expecting to happen?**

Expecting the skill to work as in the sample email Transcript.

**How is it setup** 

Deployed the Email skill as documented : [https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources/]

Created the authentication for application as [https://microsoft.github.io/botframework-solutions/skills/samples/email/]

**Can you share any logs, error output, etc.?**
Below is the conversation with the bot in Teams.

[7:00 PM] Paras Desai
    sample dialog
​[7:01 PM] rg-eu2-VA-emailskill-test-xqvnn6q
    What is your name?
​[7:01 PM] Paras Desai
    PS
​[7:01 PM] rg-eu2-VA-emailskill-test-xqvnn6q
    Nice to meet you, PS!
​[7:01 PM] rg-eu2-VA-emailskill-test-xqvnn6q
    Let me know if there's anything else you need.
[7:02 PM] Paras Desai
    show latest email
​[7:02 PM] rg-eu2-VA-emailskill-test-xqvnn6q
    Unfortunately I can't help you with that right now. Apologies.
​[7:02 PM] rg-eu2-VA-emailskill-test-xqvnn6q
    All done. Let me know if I can do anything else.

Please let me know if any more information is needed or I missed to add here.

**Comment by xieofxie** [comment]
@parasdesaicims Have you tried locally using emulator first? Could you provide related errors (like in local server, emulator etc.)? thanks

**Comment by parasdesaicims** [comment]
Yes, I have tried the same running it local and get the similar response. So in the Webchat.

- Paras!

________________________________

**Comment by xieofxie** [comment]
@parasdesaicims So I suppose you should get errors in Visual Studio when running locally? Also the traces in emulator will be useful. You could paste them here for investigation after removing private information.

**Comment by parasdesaicims** [comment]
### Long comment 

I do not get any error while running locally, the template starts as expected. The conversation from the Emulator and the corresponding JSON.
**Bot said:
How can I help you?**

JSON : 
{
  "type": "message",
  "serviceUrl": "http://localhost:57214",
  "channelId": "emulator",
  "from": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "recipient": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "role": "user"
  },
  "locale": "en-US",
  "text": "How can I help you?",
  "speak": "<speak version=\"1.0\" xml:lang=\"en-US\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xmlns=\"https://www.w3.org/2001/10/synthesis\"><voice name=\"Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)\" xmlns=\"\">How can I help you?</voice></speak>",
  "inputHint": "acceptingInput",
  "replyToId": "8229d6c0-0327-11eb-840b-17e0dabd6f00",
  "id": "84debd90-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:16:23-04:00",
  "timestamp": "2020-09-30T14:16:23.273Z"
}

**You said:
sample dialog**

**Sample Dialog JSON**
{
  "channelData": {
    "clientActivityID": "160147539041623xwzul7ovi",
    "clientTimestamp": "2020-09-30T14:16:30.416Z",
    "state": "sent"
  },
  "text": "sample dialog",
  "textFormat": "plain",
  "type": "message",
  "channelId": "emulator",
  "from": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "name": "User",
    "role": "user"
  },
  "locale": "en-US",
  "timestamp": "2020-09-30T14:16:30.431Z",
  "entities": [
    {
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true,
      "type": "ClientCapabilities"
    }
  ],
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "id": "8922f6f0-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:16:30-04:00",
  "recipient": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "http://localhost:57214"
}


**Bot said:
What is your name?**

{
  "type": "message",
  "serviceUrl": "http://localhost:57214",
  "channelId": "emulator",
  "from": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "recipient": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "role": "user"
  },
  "locale": "en-US",
  "text": "What is your name?",
  "speak": "<speak version=\"1.0\" xml:lang=\"en-US\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xmlns=\"https://www.w3.org/2001/10/synthesis\"><voice name=\"Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)\" xmlns=\"\">What is your name?</voice></speak>",
  "inputHint": "expectingInput",
  "replyToId": "8922f6f0-0327-11eb-840b-17e0dabd6f00",
  "id": "8a43d040-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:16:32-04:00",
  "timestamp": "2020-09-30T14:16:32.324Z"
}


**You said:
P**
{
  "channelData": {
    "clientActivityID": "1601475424503i65mkopz6i",
    "clientTimestamp": "2020-09-30T14:17:04.503Z"
  },
  "text": "P",
  "textFormat": "plain",
  "type": "message",
  "channelId": "emulator",
  "from": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "name": "User",
    "role": "user"
  },
  "locale": "en-US",
  "timestamp": "2020-09-30T14:17:04.518Z",
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "id": "9d743a60-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:17:04-04:00",
  "recipient": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "http://localhost:57214"
}

**Bot said:
Hi, P!**
{
  "type": "message",
  "serviceUrl": "http://localhost:57214",
  "channelId": "emulator",
  "from": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "recipient": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "role": "user"
  },
  "locale": "en-US",
  "text": "Hi, P!",
  "speak": "<speak version=\"1.0\" xml:lang=\"en-US\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xmlns=\"https://www.w3.org/2001/10/synthesis\"><voice name=\"Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)\" xmlns=\"\">Hi, P!</voice></speak>",
  "inputHint": "acceptingInput",
  "replyToId": "9d743a60-0327-11eb-840b-17e0dabd6f00",
  "id": "9df09650-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:17:05-04:00",
  "timestamp": "2020-09-30T14:17:05.333Z"
}

**Bot said:
All done. Let me know if I can do anything else.**

{
  "type": "message",
  "serviceUrl": "http://localhost:57214",
  "channelId": "emulator",
  "from": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "recipient": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "role": "user"
  },
  "locale": "en-US",
  "text": "All done. Let me know if I can do anything else.",
  "speak": "<speak version=\"1.0\" xml:lang=\"en-US\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xmlns=\"https://www.w3.org/2001/10/synthesis\"><voice name=\"Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)\" xmlns=\"\">All done. Let me know if I can do anything else.</voice></speak>",
  "inputHint": "acceptingInput",
  "replyToId": "9d743a60-0327-11eb-840b-17e0dabd6f00",
  "id": "9e2a43f0-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:17:05-04:00",
  "timestamp": "2020-09-30T14:17:05.710Z"
}

**You said:
show latest email**

{
  "channelData": {
    "clientActivityID": "1601475459336rnxcqgiubwc",
    "clientTimestamp": "2020-09-30T14:17:39.336Z",
    "state": "sent"
  },
  "text": "show latest email",
  "textFormat": "plain",
  "type": "message",
  "channelId": "emulator",
  "from": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "name": "User",
    "role": "user"
  },
  "locale": "en-US",
  "timestamp": "2020-09-30T14:17:39.357Z",
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "id": "b2383cd0-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:17:39-04:00",
  "recipient": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "serviceUrl": "http://localhost:57214"
}

**Bot said:
I’m sorry, I’m not able to help with that.**

{
  "type": "message",
  "serviceUrl": "http://localhost:57214",
  "channelId": "emulator",
  "from": {
    "id": "821d0580-0327-11eb-b7d9-39e142ec327b",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "821da1c0-0327-11eb-840b-17e0dabd6f00|livechat"
  },
  "recipient": {
    "id": "48565286-987c-4511-ac2f-9a8c9bc3a17e",
    "role": "user"
  },
  "locale": "en-US",
  "text": "I'm sorry, I'm not able to help with that.",
  "speak": "<speak version=\"1.0\" xml:lang=\"en-US\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xmlns=\"https://www.w3.org/2001/10/synthesis\"><voice name=\"Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)\" xmlns=\"\">I'm sorry, I'm not able to help with that.</voice></speak>",
  "inputHint": "acceptingInput",
  "replyToId": "b2383cd0-0327-11eb-840b-17e0dabd6f00",
  "id": "b2b3fc80-0327-11eb-840b-17e0dabd6f00",
  "localTimestamp": "2020-09-30T10:17:40-04:00",
  "timestamp": "2020-09-30T14:17:40.168Z"
}

Please check and let me know if more information is required.

**Comment by parasdesaicims** [comment]
Any updates?

**Comment by xieofxie** [comment]
@parasdesaicims If everything is fine locally, do you update `skillEndpoint`, `skillHostEndpoint` in appsettings.json when deploying? https://microsoft.github.io/botframework-solutions/skills/handbook/add-skills-to-a-virtual-assistant/

**Comment by parasdesaicims** [comment]
https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources/

**Comment by chrimc62** [comment]
Closed due to inactivity.  Please reopen the issue if you still have problems.

**Comment by parasdesaicims** [comment]
No, I've used the templates to deploy it.

**Comment by xieofxie** [comment]
Hi @parasdesaicims I have created a full check list for issues like this. https://github.com/microsoft/botframework-skills/blob/hualxie/checklist/docs/check_va_skill_oauth.md
It will help you to verify VA, skill & OAuth locally first, so we could find and identify the exception more easily.
Please check it and report any exception if you can't solve. Thanks!

**Comment by parasdesaicims** [comment]
Thanks, @xieofxie let me try that.

**Comment by parasdesaicims** [comment]
Thank you @xieofxie, it is really helpful in narrowing down the deployment and understanding Bot/skills.

# Test VA locally

- Clone [VirtualAssistantSample](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample)   **- Not sure about this one on cloning the subdirectory, Instead took the route to download and install Virtual Assistant & skill Template.**
- Deploy [VirtualAssistantSample](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources/)  **- successful**

- Check appsettings.json and it should contain microsoftAppId, microsoftAppPassword, etc.**- Yes, updated after the deployment.**
- Check cognitivemodels.json and it should contain language models etc.**- Yes, updated after the deployment.**
- Run locally in Visual Studio & [Emulator](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/5-run-your-assistant/) **- worked perfectly.**


#Test Skill locally **- Can you help on how to just clone one of the directories?**

- Clone [ToDo Skill](https://github.com/microsoft/botframework-skills/tree/main/skills/csharp/todoskill) (take todo as an example) **- Not sure about this one on cloning the subdirectory, Used the Skills.sln file and deployed only the needed ToDO skill.**
- Deploy [ToDo Skill](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/4-provision-your-azure-resources/) **- successful**
- Add [authentication](https://microsoft.github.io/botframework-solutions/skills/handbook/authentication/) if not configured correctly **- successful ( tested the connection from webapp bot)**
- Check appsettings.json and it should contain microsoftAppId, microsoftAppPassword, OAuth connections, etc.- successful
- Check cognitivemodels.json and it should contain language models etc.**- successful**
- Run locally in Visual Studio & [Emulator](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/6-run-your-skill/)  **- successfull**
- Try login and see if an exception happens **- getting an error: "Failed to generate an actual sign-in link: Error: request to https://api.botframework.com/api/botsignin/GetSignInUrl?state=eyJDb25uZWN0aW9uTmFtZSI6IlRvZG9Ta2lsbCIsIkNvbnZlcnNhdGlvbiI6eyJBY3Rpdml0eUlkIjpudWxsLCJCb3QiOnsiaWQiOiIzYjE3ZjFmMC0xYTQ2LTExZWItOWZiOC02NTdjNGM3N2FjNWUiLCJuYW1lIjoiQm90Iiwicm9sZSI6ImJvdCJ9LCJDaGFubmVsSWQiOiJlbXVsYXRvciIsIkNvbnZlcnNhdGlvbiI6eyJpZCI6IjNiMTk1MTgwLTFhNDYtMTFlYi1iYzI0LWQ5ODllZTJiZjQxOXxsaXZlY2hhdCJ9LCJTZXJ2aWNlVXJsIjoiaHR0cDovL2xvY2FsaG9zdDo1NTI4OSIsIlVzZXIiOnsiaWQiOiI4YWI0MmM1Mi02MzMxLTRlNGItODVjYy1hYWJiZTI2ZWM2YTkiLCJuYW1lIjoiVXNlciIsInJvbGUiOiJ1c2VyIn19fQ==&emulatorUrl=http://localhost:55289&code_challenge=ba70e3163b2ade39601aef20af2ab5db127a49deba501cfcfbe1ff2282bc3366 failed, reason: self-signed certificate in the certificate chain"**

#Test Skill in VA locally **- As login was having an issue skipped this step. Also, there were issues connecting Skill to VA.**

- Update skill's manifest skills\csharp\todoskill\wwwroot\manifest\manifest-1.1.json
- {YOUR_SKILL_URL} to localhost like http://localhost:3980
- {YOUR_SKILL_APPID} to appsettings.json's microsoftAppId
- [Add skill to VA](https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/7-add-your-skill/)
- Use [localManifest](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md) instead of remoteManifest this time
- Check VA's appsettings.json and it should contain BotFrameworkSkills, SkillHostEndpoint (change this to local if not)
- [Enable SSO for skill](https://microsoft.github.io/botframework-solutions/overview/whats-new/1.0/enable-sso-with-skills-using-oauthcredentials-setting/)
- Note that skill can't be used directly after this setup
- Run both VA & skill locally in Visual Studio and use Emulator to connect VA
- Try login skill and see if an error happens

# Test in Teams locally **- As login was having an issue skipped this step.**
- Configure [ngrok](https://ngrok.com/) for VA
- Set [-host-header="localhost:3978"](https://microsoft.github.io/botframework-solutions/help/known-issues/#http-500-error-when-invoking-a-skill)
- Update VA's appsettings.json's SkillHostEndpoint
- Update VA's [Messaging endpoint](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0) in Azure
- [Add to Teams](https://microsoft.github.io/botframework-solutions/clients-and-channels/tutorials/enable-teams/2-add-teams-channel/)
- [Note add token.botframework.com to Valid Domains in Domains and permissions](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample)
- Try login skill and see if an error happens
- More about [debugging](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0)

# Deploy Skill **- Works fine, login, and tasks work as expected.**

- We should already have the azure app when deploying, so publish it in Visual Studio
- Update skill's Messaging endpoint in Azure
- Try in 'Test in Web Chat' and see if an error happens
- Try help etc. Not login

# Deploy VA

- We should already have the azure app when deploying
- Update appsettings.json's SkillHostEndpoint to azure app URL
- Update appsettings.json's ToDoSkill's SkillEndpoint to skill's azure app URL **- Unable to connect the skill using remote Manifest, added the issue here:https://github.com/microsoft/botframework-solutions/issues/3669**
- Then publish it in Visual Studio
- Update VA's Messaging endpoint in Azure
- Try login in 'Test in Web Chat' and see if an error happens

# Test in Teams

- Install the app again and the URL for the bot should already be changed
- Try login skill and see if an error happens

**Comment by xieofxie** [comment]
Hi @parasdesaicims for self signed certificate in certificate chain, after some search, it could be:
- Maybe you are under a [Main-in-the-middle attack](https://en.wikipedia.org/wiki/Man-in-the-middle_attack). Someone is intercepting your SSL.
- Maybe you are in a corp network thus it uses a self signed cerficate. In this case, you could try to trust it via [some search result](https://jhooq.com/2-ways-to-fix-ssl-certificate-problem-self-signed-certificate-in-certificate-chain/#getting-windows-10-to-trust-self-signed-ssl-certificates).

For connecting the skill:
Check [--luisFolder](https://github.com/microsoft/botframework-solutions/blob/master/tools/botskills/docs/commands/connect.md) parameter. It should point to the folder one level above. If we have lg file some_path/en-us/ToDo.lu, --luisFolder should be some_path.

In your case, it could be /Users/pdesai/OneDrive-Icims,Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6/Deployment/Resources/Skills/todoskill or botframework-skills\skills\csharp\todoskill\Deployment\Resources\LU

**Comment by parasdesaicims** [comment]
Tried both ways, it's still giving the same error.

**PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU"**
Updating Dispatch
Adding skill to Dispatch
Found intent with name '*'. Adding all intents.
Parsing en-us ToDoLuModel-en LU file
There was an error while connecting the Skill to the Assistant:
Error: An error ocurred while updating the Dispatch model:
Error: There was an error in the bf luis:convert command:
Command: bf luis:convert --in "/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/ToDo.lu" --culture en-us --out /Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis --name ToDoSkill
Error: Path to /users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis (/Users/pdesai/OneDrive - Icims, Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU/en-us/users/pdesai/onedrive - icims, inc/ibots/todoskill/todoskill/deployment/resources/lu/en-us/todo.luis) leads to a nonexistent file.
**PS /Users/pdesai/OneDrive - Icims, Inc/iBOTs/MyAssistant6/MyAssistant6/MyAssistant6> botskills connect --remoteManifest "https://todoskill-t573s6h.azurewebsites.net/manifest/manifest-1.1.json" --cs --luisFolder "/Users/pdesai/OneDrive-Icims,Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU"**
Updating Dispatch
Adding skill to Dispatch
There was an error while connecting the Skill to the Assistant:
Error: An error occurred while updating the Dispatch model:
Error: Path to the LUIS folder (/Users/pdesai/OneDrive-Icims,Inc/iBOTs/TOdoSkill/todoskill/Deployment/Resources/LU) leads to a nonexistent folder.
Remember to use the argument '--luisFolder' for your Skill's LUIS folder.

**Comment by xieofxie** [comment]
@parasdesaicims I guess it couldn't handle path like `OneDrive - Icims, Inc` this properly now. Try move it to some path without comma, space?
You could tell whether it will work or not from the log: it shows the file it will process and output.

**Comment by parasdesaicims** [comment]
@xieofxie That did work, thanks. I was able to connect the skill to the VA. Trying to execute the next steps in the process and will update in case there are any issues.
