### ISSUE TITLE
Test/Bug: Overview - ps the cards work perfectly!

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#332]
Summary of testing
~~1.  Need to adjust Transcript for overview - Chat Only transcript from Excel. So for more than 2 meetings in a day: 
   **"I found [#] events for [Date]"**~~

~~2.  Align the times in the cards for overview (they wobble around - probably due to width of certain numbers and AM versus PM)~~
~~Icon for Calendar set in the middle between Title & date~~
![image](https://user-images.githubusercontent.com/43533472/97637990-f1612400-1a3b-11eb-945d-2c24b83b7db3.png)

~~3. For details on event I seem to get "Microsoft Teams Meeting" doubled (when there is no location) - in multiple events.~~
Plus the double line looks weird not sure where it comes from when opening up the chevron. 
~~Can we also take out the "," the comma after [Name], + 3 more so its [Name] and 3 more (less interruptive to the eye)~~
![image](https://user-images.githubusercontent.com/43533472/97638002-fb832280-1a3b-11eb-9e5c-a036993bb6c5.png)
![image](https://user-images.githubusercontent.com/43533472/97638022-0473f400-1a3c-11eb-8d19-4675b12a194d.png)

~~1. Are we also able to show the + 3 more? Idea was you could open up also (like the chevron), if that's not possible maybe just a list with contacts (max of 10 + # more)~~
![image](https://user-images.githubusercontent.com/43533472/97989780-4eaff900-1ddf-11eb-888a-e598ba8c70ee.png)

4. (refer to #364) Asking about next week/month no response, weekend works great (with carrousel for saturday/sunday)
![image](https://user-images.githubusercontent.com/43533472/97638063-18b7f100-1a3c-11eb-89fd-a00c55e10e3b.png)

5. ~~Search/Find takes long time feels like no response - maybe we can include 
**"I'm searching your calendar, this might take a sec"
"Hold on, I'm trying to find events that match"**~~

6. (refer to #365) Paging (find) does not work, it auto populates a new card and logic is weird now - can we try the update status
![image](https://user-images.githubusercontent.com/43533472/97638077-1fdeff00-1a3c-11eb-962f-3c57c74524b4.png)

7. (refer to #366) For create flow, it's the voice script which is fine, but do we want to call that out? I think it's nice to highlight there will be a Teams form - otherwise we will get that feedback probably.
- (refer to #367) Select attendee, the click is not working, you need to call out the number or exact surname
- ~~The total amount of contact does not match the list~~
![image](https://user-images.githubusercontent.com/43533472/97638382-b90e1580-1a3c-11eb-8c20-7ec8b9d06fcc.png)

~~8. Suggestion for time date is not working in my test, the default should then not even ask this question I think? Just ask:
 **"What date and time did you have in mind?"**
 **"When should the event start?"**
 **"And what date?"**~~
![image](https://user-images.githubusercontent.com/43533472/97638474-e1960f80-1a3c-11eb-815d-bafdcc7d3b3c.png)
fixed #334

~~9. With voice this step makes sense, but with chat it's a bit doubled  - can we take out the additional ask are you sure?~~
![image](https://user-images.githubusercontent.com/43533472/97638942-ec9d6f80-1a3d-11eb-837a-195874a242d9.png)
fixed #334

~~10. Summary for create, everything is showing and correct (time, date, Teams link) except the attendees in the summary.~~
fixed https://github.com/microsoft/botframework-skills/pull/349

**Comment by KayMKM** [comment]
@Quirinevwm could you post a screen shot for the 10th issue?

**Comment by Quirinevwm** [comment]
> @Quirinevwm could you post a screen shot for the 10th issue?

Sure, here you go - I'll add some more bugs relating this too:
![image](https://user-images.githubusercontent.com/43533472/97873426-e5b17e00-1d17-11eb-941c-6fa1195fac5c.png)

11. When user says no to create, need other transcript then: "Event creation failed", have a look at transcript Excel
**> Yes
- Alright, your event has been created.
- I've added the meeting on your calendar.
- OK, the event has been created for you. 

> No
- OK, I've not send out this event. 
- No problem, the event has not been created.**

12. Can we include the interruption also at the last stage when we call out the details before sending out, so when a users asks update the (title, include another attendee, change the duration) - that this works

**Comment by xhr0804** [comment]
@Quirinevwm  For 13 and 21, I can not reproduce it, could you give more information or double check it?

**Comment by Quirinevwm** [comment]
> @Quirinevwm For 13 and 21, I can not reproduce it, could you give more information or double check it?

Sure! For 13, when you search for meetings will do it again:
![image](https://user-images.githubusercontent.com/43533472/97985182-34265180-1dd8-11eb-87e2-61db182cee53.png)
The sure text is gone this time, but it's still taking quite long maybe include some sub text plus the "next page" if we hide that out it makes sense that we just share the first line of transcript (include : semicolon at the end then) so **"I've found 18 events that match your request:"**
This is overkill and only confusing: 
![image](https://user-images.githubusercontent.com/43533472/97985365-7bacdd80-1dd8-11eb-8be7-00780862d2ad.png)

21. For today it works like this:
![image](https://user-images.githubusercontent.com/43533472/97985634-cf1f2b80-1dd8-11eb-91ba-bc1b8462eeea.png)

**For tomorrow**, it shows the date (we can take that out and just ask for time). If there are multiple it does not show the options in the list just one:
![image](https://user-images.githubusercontent.com/43533472/97985811-0d1c4f80-1dd9-11eb-8def-20f06c4fe110.png)

if there is one meeting, now does not show the "time left" transcript but the correct one:
![image](https://user-images.githubusercontent.com/43533472/97985967-4ce33700-1dd9-11eb-95ef-ae5c5327f67b.png)

if I try again for tomorrow: transcript shows no location provided - whilst it contains a Teams link please update right transcript:
![image](https://user-images.githubusercontent.com/43533472/97986145-96338680-1dd9-11eb-955f-daa0d0c0e9fd.png)

For other day in the week: take out options in the past, then showing date makes sense!
![image](https://user-images.githubusercontent.com/43533472/97986353-df83d600-1dd9-11eb-823a-7c3052588930.png)

**Comment by KayMKM** [comment]
@Quirinevwm  the 8 and 19 are same issue. and which action should I take?

**Comment by Quirinevwm** [comment]
> r

Yes the duplicate we discussed yes, plus I will add the updated bugs in the backlog as separate for you - will reply to Brenda's too that relate to the ones in this list!

**Comment by KayMKM** [comment]
@Quirinevwm I can't repro the clicking not work issue in 7th. Can you try again?

**Comment by xhr0804** [comment]
@Quirinevwm For the 4th issue, the bot can respond in the emulator:
![image](https://user-images.githubusercontent.com/44257569/98217200-23670e80-1f85-11eb-9eb3-10455ddf4170.png)
But meetings of different day will be displayed separately.
In Teams, it will fail due to the large size of cards.
![image](https://user-images.githubusercontent.com/44257569/98217799-ef401d80-1f85-11eb-94e9-7c65941a49cd.png)

**Comment by Quirinevwm** [comment]
> @Quirinevwm I can't repro the clicking not work issue in 7th,15th and exception in 17th. Can you try again?

I've answered/explained what is meant with these issues in https://github.com/microsoft/botframework-skills/issues/343#issuecomment-722341404 

I'm stuck here though - so I can't try again
![image](https://user-images.githubusercontent.com/43533472/98241176-daa25c00-1f6a-11eb-9f91-cf80392fea74.png)

**Comment by Quirinevwm** [comment]
> ay will be displaye

In the design & transcript file we have different utterances and logic for:
- **weekend** = show saturday/sunday in carrousel (that works in Teams load)
**For the weekend, I see you have [#] events:**
**I see you have [#] events planned in the weekend:**
Shows card for saturday/sunday

- **week/month** = show just the upcoming Monday + additional transcript:
**Next week, I see you have [#] events. First up on Monday:
Next month, I see you have [#] events. First up on Monday:**
Shows card for monday

![image](https://user-images.githubusercontent.com/43533472/98241793-c0b54900-1f6b-11eb-80d4-599707394380.png)

**Comment by xhr0804** [comment]
Close for separate track
