### ISSUE TITLE
Click next page for meeting list, it will be response in quite a long time

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-components#342]
## Version
calendarv2

## Describe the bug
- "find tomorrow meeting" , it will show the meeting list (eg. on my list I have 15 events)
-  click next page
- it will hide the card and then show it again.  The intervals is quite long, I wait for 3-5 seconds to see the card show again. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by Quirinevwm** [comment]
#332 , number 5 on overview list, I've added transcript for this load state.

**Comment by lauren-mills** [comment]
Working on switching to the Teams Update action instead of delete/replace.
