### ISSUE TITLE
meeting detail info missed if choose from the meeting list 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-components#343]
## Version
calendarv2

## Describe the bug
- find tomorrow meeting
- click next page
- then select one meeting item
- it does not show any meeting detail info
![image](https://user-images.githubusercontent.com/43408889/98087994-e125ca80-1ebb-11eb-920c-45d8c870c247.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by Quirinevwm** [comment]
#332 same as 7&15, yue is working on making sure the list works for: 

- click on element, 
- full call out of option,
- first/second/third/fourth/fifth (1,2,3,4,5) work

**Comment by lauren-mills** [comment]
I wasn't able to repro this. I was able to click the next page and select one of the meetings and show the details. Do you have any more information?

**Comment by Quirinevwm** [comment]
> I wasn't able to repro this. I was able to click the next page and select one of the meetings and show the details. Do you have any more information?

I think what Brenda is referring to, what I also experienced with **Calendar overview** - is the card works with paging (so clicking on the ui for paging gives next page), but the rest does not work smoothly for selecting a meeting:
- in the overview when I click on a meeting (the one below pops up with details)

For the other cards (contacts, suggestions) the following did not work:
- Clicking on the element
- Calling out the name
- Saying first/second/third/fourth/fifth (1,2,3,4,5) 

I'm trying to reproduce but I can't seem to get my overview working:
![image](https://user-images.githubusercontent.com/43533472/98239622-84ccb480-1f68-11eb-896c-9a25122ca29e.png)

Ps. can we make sure we do not show "I'm searching your calendar, this might take a sec... twice, I have added additional versions in the #333 (branded content section)
