### ISSUE TITLE
Update meeting - "Request size too large" error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-components#344]
## Version
calendar v2

## Describe the bug
![image](https://user-images.githubusercontent.com/43408889/98088395-58f3f500-1ebc-11eb-9b53-3e4f96908d74.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by KayMKM** [comment]
@Quirinevwm do we need a maximum of search results?

**Comment by Quirinevwm** [comment]
> @Quirinevwm do we need a maximum of search results?

In general in all list designs, we went for showing 25 max, so 5 pages. 
We can in the transcript state you have [211] events, but only show 25 in the card. Up for debate if we call that our specifically that we only show 25).  

Hence, why we have specific transcript too when you hit the end of 25 options - when there is more to show at the end we can prompt & highlight a new button with show more.

**Comment by xhr0804** [comment]
@xhr0804 @KayMKM Please limit the max number to 25 for meeting/contact/timesuggestion list.

**Comment by xhr0804** [comment]
This is blocked because cross-train feature doesn't work in current composer version. Cann't be fixed until next release
https://github.com/microsoft/BotFramework-Composer/issues/4960

**Comment by bobokids** [comment]
Please validate the issue after Composer build is ready.
