### ISSUE TITLE
Test/Bug: ask for overview today when no meetings are planned anymore - Bad request

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#358]
Scenario: user asks about what is on for today/tonight, there are no meetings on the calendar anymore, so they should receive a transcript with:
(see transcript for no meetings & end of day)

_Recognize that it's before noon (12 PM)_
**You don’t have anything planned on [Date].
For [Date], you don't have anything scheduled yet.
No meetings on [Date] yet.
You don't have anything on [Date].**

_Recognize that it's after noon (12 PM)_
**That's it for [day]. 
There aren't any other events planned. 
That's the end of your planned events.** 

Now I just get a bad request (since there are no meetings)
![image](https://user-images.githubusercontent.com/43533472/98245702-9ebec500-1f71-11eb-8a5c-28b2fe448912.png)

**Comment by lauren-mills** [comment]
I was not able to repro this. Do you have any more information about what you tested? I cancelled all my meetings for the day then asked "what's on for today" and it shows this:
![image](https://user-images.githubusercontent.com/27976702/98288097-2c42ea80-1f5b-11eb-8aa1-529d19776f83.png)
