### ISSUE TITLE
Test/Bug: Search for meeting at a certain time works well, maybe we can include if it's organized by yourself that we show - "you are the organizer"

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-components#371]
Search for meeting at a certain time works well, maybe we can include if it's organized by yourself that we show - "you are the organizer"
![image](https://user-images.githubusercontent.com/44257569/98519968-6e965f80-22ac-11eb-977e-66bedb23c815.png)

**Comment by xhr0804** [comment]
@Quirinevwm the card shows both "You are the organizer"(in response state field) and name(in attendees field) now.
Do you think we should not add the organizer himself into the attendee field and remove the attendee field in this scenario?
![image](https://user-images.githubusercontent.com/44257569/98753557-964a0c80-23ff-11eb-9eb9-81335f9cf8c4.png)

**Comment by Quirinevwm** [comment]
@xhr0804 I've update the "you are organizer" design as following:
![image](https://user-images.githubusercontent.com/43533472/98812901-a2e05c00-2423-11eb-9ec2-cffa6fe81f05.png)
