### ISSUE TITLE
 Find event - Update response to include search parameters

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#389]
Refer to specific transcript related to a specific find action:
So when a user asks about their meetings with Alex

Show:
I've found #events with [Name=Alex]:
![image](https://user-images.githubusercontent.com/43533472/98850808-9b39ab00-2455-11eb-858d-13d42d8f9dbf.png)

**Comment by xhr0804** [comment]
This may need further discussion for the condition may not be that easy to display for us.
There are some problems:
1. Condition in user input could be a very simple spelling like 'alex', but when that may be 'Alex Wilber' after we find it. For with time/title, things could be more complex.
2. User may also provide more than one condition, like with whom at when with some title, in that case we may need more detailed design

**Comment by Quirinevwm** [comment]
@xhr0804 yes I see the difference you are referring to, and what is the priority of elements we highlight with search if they provide more conditions. Proposal would be to:
1. In transcript, call out we recognize they are searching for a:
- contact (who?). "I've found #events with [Contact Name(s)]:"
- title meeting (what?): "I've found #events named [Title]:"
- time/date (when?). "I've found #events on [Time/Date]:"
- location (where?). "I've found #events at [Location]:"

![image](https://user-images.githubusercontent.com/43533472/100632565-4343e500-332d-11eb-9b37-c7ba0e858821.png)

2. Order I propose we call out the factor that users recognize the most - bot picks up their search. Then we are not putting too much complexity in the transcript, **we do filter on all the conditions we pick up though!** So that means they will see the filtered list of the search - the transcript will just describe one condition for simplicity.
I've proposed an order in point 1 if they include multiple conditions in their search: 
1. Contact transcript
2 Title
3. Time/Date
4. Location

**Comment by lauren-mills** [comment]
Moving this to a note in the backlog until we decide to commit it
