### ISSUE TITLE
Find attendees - show context specific response with attendees names

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#392]
For now our design highlights times/dates and titles -> for details that include attendees the user needs to click on the element to see more. 

If a user utters: **"who will I meet for my lunch meeting tomorrow?"**
The bot should reply back with: **You are meeting with [Name] and # more, at 01.00 AM.**

![image](https://user-images.githubusercontent.com/43533472/98851920-3717e680-2457-11eb-968e-bd2dc3e8b3ae.png)

**Comment by lauren-mills** [comment]
I think this is a LUIS training issue. We already have the logic to call out the attendees if that intent is detected so I think this is just triggering the wrong thing

**Comment by lauren-mills** [comment]
Added as note to the backlog
