### ISSUE TITLE
[Calendar Skill V2] strange search result for attendee

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-components#401]
## Describe the bug

When searching for Wu qiong, it returns a 'no-reply':
![image](https://user-images.githubusercontent.com/2876650/99351625-f9461280-28db-11eb-8761-79ad70c05409.png)

**Comment by xhr0804** [comment]
Can not repro this, it's weird
![image](https://user-images.githubusercontent.com/44257569/99938196-40cc1300-2da2-11eb-8369-506cbf672854.png)

**Comment by xieofxie** [comment]
Seems a bug for [contacts api](https://docs.microsoft.com/en-us/graph/api/contact-get?view=graph-rest-1.0&tabs=http) + [search](https://docs.microsoft.com/en-us/graph/query-parameters#odata-system-query-options)

**Comment by bobokids** [comment]
Tracked as external issue.
