### ISSUE TITLE
GetLocation interruption needs more training data

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-components#404]
## Describe the bug

I would only want to create an online meeting, but it seems redirect to search:
![image](https://user-images.githubusercontent.com/2876650/99353442-77f07f00-28df-11eb-9e8a-ff2b0c98a94d.png)

**Comment by xhr0804** [comment]
need to enrich the utterances of Skip intent in create meeting flow.

**Comment by bobokids** [comment]
Lauren, please help to handle the LUIS related issues.
