### ISSUE TITLE
Add typing middleware

### ISSUE THREAD

**Issue by mewa1024** [microsoft/botframework-components#407]
## Describe the bug
In the Calendar card, the cursor turns to a pointer when I hover over links, but there is no underline and no change in appearance when I click. When I tried this, there was about a 2 second lag between when the link is pressed and the event card appeared, so I clicked the links 9 times before the cards appeared. Then all 9 cards appeared at once, pushing my Calendar card out of view.

## To Reproduce
1. Ask for the the days schedule.
2. Click on the time or name of an event.

## Expected behavior
I'd expect an underline to appear on hover to reinforce that the text is a link. It would be nice to having some affordance when the link is pressed, or something to indicate that the skill is doing something, like the ... to indicate typing. It took about 2 seconds for the card to appear, which is a little long without feedback.

## Screenshots
Below is the Calendar card. I clicked on the event times and name repeatedly before the cards had a chance to appear.
![image](https://user-images.githubusercontent.com/39317542/99442945-f3960000-28ce-11eb-91d3-2daa2fa5bbc1.png)

**Comment by lauren-mills** [comment]
Thanks, @mewa1024! Unfortunately Teams and Adaptive Cards controls the rendering for the cards themselves so we don't have control of any "hover" action. We should be able to add typing indicators though which is a small step in the right direction.
