### ISSUE TITLE
[Calendar Skill V2] "edit my event" did not find an event I created

### ISSUE THREAD

**Issue by mewa1024** [microsoft/botframework-components#408]
## Describe the bug
When I created an event and then tried to edit the event with the text "edit my event", it was unclear whether the skill found the event I was looking for.

## To Reproduce
Here is the conversation:
![image](https://user-images.githubusercontent.com/39317542/99443778-2391d300-28d0-11eb-8167-81f8185fc4b5.png)
![image](https://user-images.githubusercontent.com/39317542/99443864-3efcde00-28d0-11eb-935e-c0326b85bda3.png)
![image](https://user-images.githubusercontent.com/39317542/99443944-60f66080-28d0-11eb-9777-c3afc7cfd33d.png)

Adding an event working, but searching was unclear. The skill replied with "I see you are not the owner of the meeting. Would you like to update your response?" but did not specify which meeing, so I didn't want to edit it.  

I tried these utterances to get the skill to tell me the name of the meeting it was referring to:
"which booking?"
"show meeting"

## Expected behavior
I expected the skill to find the meeting that I just created and show me a card. If it found no meeting, I would expect it to say it found no meeting.

**Comment by KayMKM** [comment]
Calendar skill doesn't support context share now. So after create you said "edit the event" it will trigger a new update flow. I tried this scenario but didn't repro your issue
![image](https://user-images.githubusercontent.com/19773357/99946709-c99e7b00-2db1-11eb-810d-12113fa2b814.png)
![image](https://user-images.githubusercontent.com/19773357/99946755-de7b0e80-2db1-11eb-91c5-a33891877fba.png)
![image](https://user-images.githubusercontent.com/19773357/99946783-e9ce3a00-2db1-11eb-8aed-36a0cc1ee02b.png)
