### ISSUE TITLE
Custom actions - refactor MSGraph custom action

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#437]
## Describe the bug
Refactor MSGraph custom action in calendar skill V2 to make it more readable, and cleanup/refactor any code that is redundant.

## To Reproduce
It's refactoring so there isn't a need to reproduce.

## Expected behavior
No behavior change expected.

**Comment by hcyang** [comment]
Hi Thomas,
Not sure how this came up in today's DRI review, but please create an internal work item for triage. Thanks.
