### ISSUE TITLE
News sample skill returns unauthorized error

### ISSUE THREAD

**Issue by bAbdulaal** [microsoft/botframework-components#441]
## Version
I am using bot framework v4, GA1.0

## Describe the bug
I am trying to use the experimental skills provided by the bot framework. I downloaded the code for the [news skill](https://microsoft.github.io/botframework-solutions/skills/samples/news/) and created all azure resources. I got the bing key from [here](https://www.microsoft.com/en-us/bing/apis/bing-news-search-api) and placed it in my appsettings.json I also updated all my config values to my Luis app. I am testing through emulator. When I run the code I go through the dialog successfully, it asks me for the topic I want to get news about and my country and then at the point where it has to get the news articles I get the following error.

![image](https://user-images.githubusercontent.com/46318511/101353560-768df300-389c-11eb-9406-b9ebee57d75a.png)

## To Reproduce
Download news skill code (https://microsoft.github.io/botframework-solutions/skills/samples/news/) 
Create azure resources on portal
Update config values in appsettings.json and cognitivemodels.json
Deploy the app
Run in emulator

## Expected behavior
News articles should be successfully returned to the user

## Screenshots
![image](https://user-images.githubusercontent.com/46318511/101353733-c4a2f680-389c-11eb-84b8-483d23537ffc.png)

**Comment by tonyanziano** [comment]
@lauren-mills can you please take a look at this?

**Comment by lauren-mills** [comment]
Hi @bAbdulaal, did you provide both the Bing Key and the Azure Maps key?

**Comment by bAbdulaal** [comment]
Yes, I have provided both Bing and Azure Maps key in my appsettings.json

**Comment by gabog** [comment]
Hi @thomas-chung, can you take a look at this one while lauren is out?

Thanks

**Comment by thomas-chung** [comment]
Sure thing. @bAbdulaal please stand by while I look into the issue.

**Comment by thomas-chung** [comment]
@bAbdulaal We are getting close to the root cause of the issue. Our theory is that the News Skill is currently using an old version of the Bing Search API library is not compatible with the new V7 version of the API. We are currently evaluating a short term workaround and a longer term fix.

Will update you as we complete the investigation and provide you with update/instruction.

**Comment by thomas-chung** [comment]
Hi @bAbdulaal this issue has been verified as related to a recent migration from Azure Cognitive Service to the Bing Search API per following message on the API reference documentations (https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v7-reference):

> Bing Search APIs are moving from Cognitive Services to Bing Search Services. Starting October 30, 2020, any new instances of Bing Search need to be provisioned following the process documented here. Bing Search APIs provisioned using Cognitive Services will be supported for the next three years or until the end of your Enterprise Agreement, whichever happens first. For migration instructions, see Bing Search Services.

The news skill internally consumes the Bing News API C# component which is no longer published/maintained. The component internally makes RESTful calls to either "https://api.cognitive.microsoft.com" but can be overridden to "https://api.bing.microsoft.com/". However, the new REST URLs also has changes as well to the relative path. This cannot be mitigated easily and as such a different work around is being pursued.

I am working on a change to push (see attached PR) to the main branch to essentially rewrite the URI on the fly to update the path should we detect the host is now api.bing.microsoft.com. This would then allow the call to proceed as normal. Note - there is no major changes to the JSON response model so the skill should continue to work as is.
