### ISSUE TITLE
Validate runtime against calendar skill

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botframework-components#443]
- [x] Migrate to adaptive runtime with custom actions enabled and validate
- [x] Test with skill configuration auth changes
    - [x] As a host
    - [x] As a skill
- [x] Add additional tests for calendar skill specifically, if required
- [x] Port skill configuration changes to runtime lib
- [ ] Roadmap for rest of changes required to use adaptive runtime
- [x] Define scenario: I can run the Calendar Skill (runtime + custom actions using auth) as a regular but only via Composer
- [x] Define scenario: I can connect to the Calendar Skill as a local skill added to my core bot .botproj
- [x] Define scenario: I can connect to the Calendar Skill as a remote skill added to my core bot .botproj

**Comment by ryanlengel** [comment]
- [ ] Migrate to adaptive runtime with custom actions enabled and validate
- [ ] Test with skill configuration auth changes
    - [ ] As a host
    - [ ] As a skill
- [ ] Add additional tests for calendar skill specifically, if required
- [ ] Port skill configuration changes to runtime lib
- [ ] Roadmap for rest of changes required to use adaptive runtime

**Comment by ryanlengel** [comment]
Tracking progress on original post. I've validated the calendar's runtime in general and with changes in upcoming pull requests (regarding authentication configuration).
