### ISSUE TITLE
[Calendar Skill V2] Tests failing on calendarskill_v2 branch

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#448]
## Describe the bug
14 out of the 26 Calendar Skill tests are failing on the calendarskill_v2 branch. 

## To Reproduce
Run tests out of the box. 

## Expected behavior
All tests should pass out of the box. If there is additional configuration required to run successfully, it should be included in README documentation. If the test dialogs are out of sync, they should be updated accordingly.

## Screenshots
![image](https://user-images.githubusercontent.com/43043272/101550977-16af4f00-3965-11eb-893d-aa4292980fd0.png)

**Comment by KayMKM** [comment]
the test cases won't be fixed due to re-review required by feature team.
