### ISSUE TITLE
Conversational Core template should rename assistant.dialog

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#451]
The Conversational Core template creates an assistant.dialog file, whose name as is appears in Composer is also 'Assistant'. When creating a new bot using this template, the template should:

- Rename the assistant.dialog file to something more suitable
- Ensure the name of the dialog reflects user input/made more generic

**Comment by ryanlengel** [comment]
This is resolved with generators using the botName variable, marking as resolved.
