### ISSUE TITLE
Conversational Core template - common.en-us.lg should reference image from official location

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#452]
In the Conversational Core template, the included common.en-us.lg file includes an image URI to the following location at line 90: https://raw.githubusercontent.com/ryanlengel/adaptivecards/master/assets/icons/e787-32.svg

We should ensure to update this to an official location to reference the image from.

**Comment by ryanlengel** [comment]
We can remove this entirely, the card this is used in came from a demo of showing a card with various skills connected. The package shouldn't have this icon or card as it assumes specific skills are connected to the bot as well.

**Comment by ryanlengel** [comment]
Removed in latest generator
