### ISSUE TITLE
Create a template that includes a core dispatcher + a calendar bot

### ISSUE THREAD

**Issue by benbrown** [microsoft/botframework-components#477]
Now that we have a functional yeoman template system for creating new bots in Composer, we should validate that we can create a multi-bot project.

**Comment by clearab** [comment]
Can we please not publish this? I do not think this is a pattern that we should be encouraging developers to follow (File > New Bot > end up with more than one bot). When calendar/who functionality is pulled into a template, it should be pulled in as a package and executed in-proc. If we want to validate that this is possible awesome, but this shouldn't be the normal scenario for when/how skills are added.

**Comment by benbrown** [comment]
We will not be publishing this - this is to test the e2e system.

**Comment by benbrown** [comment]
this is in main now as `generator-multibot`
