### ISSUE TITLE
Create a package for including Orchestrator with 64/32 bit selection (default: x64)

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-components#479]
We need a new package to include Orchestrator "component" with architecture selection.

**Comment by scheyal** [comment]
Context:
Composer builds dotnet as AnyCPU. Orchestrator is architecture dependent due to native libs requirements. As such, Composer builds fail for users who want to build 32 bit bots (smaller subset, but important such as in free SKUs).
For R12, we should have a component that brings in Orchestrator with architecture option. It shall download the assemblies, and result with modified generated code so that Orchestrator snippet and assemblies are included.

**Comment by clearab** [comment]
I don't think this is possible - the package can't dictate the chip architecture (or as far as I'm aware declare a dependency on a particular chip architecture). Is this just updating the existing Orchestrator package with .dll's compiled against x86 and x64 architecture?

**Comment by clearab** [comment]
Closing.
