### ISSUE TITLE
Command List template

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#491]
**Friendly Name** 
Command list bot

**Name** 
Microsoft.Bot.Template.CommandList

**Description**
A bot using simple regular expressions and cards actions to respond to a set of commands.

**Purpose**
The base bot for all developers that do not wish to start with an NLP like LUIS, but rather use a card and/or regex approach to handling interactions. It is the regex version of the Conversational Core bot. 

**Functionality**
- On first run, send a card "Type help or hello, or click the buttons below" with message back actions for "Help" and "Say hello"
- Respond to any message containing help with the help dialog
- Respond to any message containing hello with the hello dialog
- Respond to any other message with unknown intent dialog that gives a "sorry" message, then sends the first run card
- Help dialog is modeled after the conversational help package, ends with sending original card
- Hello dialog says hello, then sends original card

**Dependent packages**

None

**Comment by sgellock** [comment]
I don't want to ship this as a package.  I'd like to see it go out as a sample that could be build by customers who seek out a solution the problem it's positioned to solve
