### ISSUE TITLE
QnA Maker template

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#498]
**Friendly Name** 
QnA Maker

**Description**
A template for creating a bot that connects to a QnA Maker knowledge base.

**Purpose**

A basic bot for folks that want to connect to an existing KB, or create a new one.

**Functionality**
- Uses QnA Maker trigger
- Post creation landing page should explain how to
  - connect to existing kb
  - edit qna file
  - provision/deploy new kb and edit on web

**Comment by pavolum** [comment]
Closing this as it is reopened in the Composer repo (#5797 in Composer Repo)
