### ISSUE TITLE
[R13] Feature: Assistant Core template

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#500]
### Summary
A template for creating an assistant-style bot, with advanced conversational interactions.
The base bot that we can build the vertical-specific templates from (like enterprise assistant). The place for customers to start who want to build advanced conversational bots that can perform multiple distinct functions.

### Package Details
- **Package Name** - @microsoft/generator-bot-assistant-core
- **Display Name** - Assistant Core
- **Description** - TBD
- **Keywords** - TBD
- **Supported Languages** - C#
- **Supported Locales** - en-US

### Components
⚠**The screenshots below are mockups** demonstrating the skeleton of the template and contain untested logic⚠

The following list of components should be referenced out of the box:
- [x] #736 **ChitChat**
_Professional personality with QnA trigger, likely enabled as part of the OnIntent (Unknown) logic. If this content is added to_
![image](https://user-images.githubusercontent.com/43043272/110863993-593f3b00-8276-11eb-9d2e-b96aa40dc1e6.png)
![image](https://user-images.githubusercontent.com/43043272/110864706-542ebb80-8277-11eb-9e19-7e7979c38718.png)

- [x] #738 **Feedback**
_Simple feedback dialog that logs to telemetry_
![image](https://user-images.githubusercontent.com/43043272/110864499-116ce380-8277-11eb-8b0a-e12cf08153aa.png)

- [x] #468 **Onboarding**
_Simple "bot tour" dialog triggered in greeting_
![image](https://user-images.githubusercontent.com/43043272/110864894-99eb8400-8277-11eb-9b20-ffaa8a596388.png)

- [x] #741 **Greet new and returning users**
_Greeting dependent on Onboarding package (more advanced than the Welcome component used in Conversation Core)_
![image](https://user-images.githubusercontent.com/43043272/110865377-60ffdf00-8278-11eb-8176-0448765079e2.png)
![image](https://user-images.githubusercontent.com/43043272/110865534-a02e3000-8278-11eb-97a9-bbd66331af26.png)

- [x] **HelpAndCancel**
_Handle help and cancel utterances (from Conversation Core)_
  - [x] #683 
  - [x] #681 
  - [x] #682 
![image](https://user-images.githubusercontent.com/43043272/110866581-357df400-827a-11eb-8b9e-38774a46f2bb.png)
![image](https://user-images.githubusercontent.com/43043272/110866252-b688bb80-8279-11eb-8949-2e87e7015aee.png)

### Additional Requirements
- [x] #735 **Auth/Single sign-on**
_A developer is able to [enable single sign on](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml) without making any changes to their runtime code_

- [x] #737 **Disambiguation**
![image](https://user-images.githubusercontent.com/43043272/110867409-8b06d080-827b-11eb-8ec9-46407e2680a8.png)

- [x] #689 **Error handling**
_Provide default error handling implementation in Conversation Core template and all those derived from it)_
![image](https://user-images.githubusercontent.com/43043272/110866728-72e28180-827a-11eb-9a89-d89d0c40d2ad.png)

- [x] **Unknown intent** 
_Handle unknown intents, this may use ChitChat as a fallback as the dataset should not be loaded into LUIS or Orchestrator_
![image](https://user-images.githubusercontent.com/43043272/110868079-bf2ec100-827c-11eb-965e-31a71ee333d9.png)

**Comment by ryanlengel** [comment]
My assessment on work items based on what we have in the functionality list:

Creation/Template
* Requires storage, default is CosmosDB
* Telemetry and transcript logging should be enabled
* Typing indicate enabled (unless this needs redesign, in which it would likely be a component)

Components
* Help from QnA trigger
* Cancel
* Auth (SSO w/ fallback) (declarative assets, custom actions)
* Terms & Conditions (declarative assets)
* Simple feedback (declarative assets)
* Disambiguation (not sure)
* Personal data management (declarative assets, custom actions)
* Onboarding (declarative assets)
* Chit-chat (declarative assets)

**Comment by tracyboehrer** [comment]
https://microsoft.sharepoint.com/:w:/r/teams/ConversationalAI785/_layouts/15/guestaccess.aspx?e=c9Rkny&CID=2EE63D4D-5FCE-4F12-94EE-FAB96EE54B17&wdLOR=cCF2C0679-35F9-4B32-A2D2-71D211D7A3C7&share=EXkPH_cKwChAiuhQzYnfUnYBPaXwlv102fUr1aMrIf6zsA

**Comment by ryanlengel** [comment]
I've update the issue with an updated template, linked issues, and screenshots of a dummy bot I worked on. This can be used to facilitate direction of the template, shared here:
[assistantCore_export.zip](https://github.com/microsoft/botframework-components/files/6126473/assistantCore_export.zip)
