### ISSUE TITLE
Refactor QNA template

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-components#574]
At current state the qna template is really using the empty-bot-generator under the hood.

For consistency sake it may be best to make a generator for this template that calls the empty bot generator with ComposeWith.

That way we do not write redundant package code and can have the qna template grow to have more enriched features.

**Comment by clearab** [comment]
+1 to this - we also need a place to keep the QnA readme, and there is no guarantee there won't be drift between theses things in the future.

**Comment by ryanlengel** [comment]
Related to #498

**Comment by ryanlengel** [comment]
Related to #730

**Comment by pavolum** [comment]
Closing as this is a duplicate of 730
