### ISSUE TITLE
All future generators that create multi-bot projects should generate a single sln file 

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#616]
When I run `yo multi-bot TestMultiBot` I end up with two solution files and each one references the underlying botproj:

## Current file system layout: 
![image](https://user-images.githubusercontent.com/12264946/108868517-4a912c80-75c4-11eb-8eb6-a106348d9890.png)

### calendar.sln
![image](https://user-images.githubusercontent.com/12264946/108868761-888e5080-75c4-11eb-9fb5-5bda3369659a.png)

### TestMultiBot.sln
![image](https://user-images.githubusercontent.com/12264946/108868880-a065d480-75c4-11eb-8e96-d906f877839f.png)

## Expected behavior
The normal flow for visual studio would be to create a single sln file with both project in it:

### Expected file system layout:
![image](https://user-images.githubusercontent.com/12264946/108869021-d0ad7300-75c4-11eb-83d7-094b74cc0fd2.png)

### Expected sln:
![image](https://user-images.githubusercontent.com/12264946/108869147-e753ca00-75c4-11eb-9505-436bdc79e92e.png)

It is also important to note that calendar, does not follow C# naming guidelines and should have been Calendar (PascalCase) which result in improper namespaces:
![image](https://user-images.githubusercontent.com/12264946/108869822-91335680-75c5-11eb-96bc-245372241e50.png)

**Comment by tracyboehrer** [comment]
This appears to work like this for Enterprise Assistant.  Would this be true of all current multibot generators?

**Comment by lauren-mills** [comment]
AFAIK enterprise assistant is the only multi-bot template that we're planning to ship.

**Comment by lauren-mills** [comment]
Closing since this is done for EA
