### ISSUE TITLE
Improve exception handling in Runtime bot

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#617]
We should review [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1) and follow the recommended approach for the platform.

**Comment by tracyboehrer** [comment]
- Add ILogger to IBotPluginLoadContext
- app.UseExceptionHandler?

**Comment by tracyboehrer** [comment]
Split into separate issues:
https://github.com/microsoft/botbuilder-dotnet/issues/5311
https://github.com/microsoft/botframework-components/issues/743

**Comment by peterinnesmsft** [comment]
@tracyboehrer @gabog is there anything left that we're tracking with this issue? Looks like it was split into multiple issues that are all now closed. Can we close this one?

**Comment by gabog** [comment]
This has been addressed in other PRs closing it.
