### ISSUE TITLE
[Calendar Skill V2] : update 'Sign in' messaging

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#629]
## Describe the bug
Sign-in Teams desktop does not work, need to open up in browser for auth. Let's communicate this in the 'Sign in' card. Plus align to have the same font as the 'Hi message'

## Expected behavior
- Same font size as 'Welcome'
- Update content:
Time to sign in with your Microsoft account to access your calendar 🗓.
For this dogfood please sign in via Teams in your preferred browser: https://www.microsoft.com/en/microsoft-teams/log-in.

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/108995244-1473ab80-769d-11eb-817c-ec3b3a925a6e.png)

**Comment by lauren-mills** [comment]
The sign in card doesn't let me change the size of the text, since that is set by the client.

I'm going to leave this in the backlog until I have a chance to test SSO
