### ISSUE TITLE
[Calendar Skill V2] : Card 'Overview' space time table

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#630]
## Describe the bug
Really like the new compact card aligning to the adjustments :)
The alignment of time to the right makes it readable so definitely stick to that, plus I see the max 10:00 - 11:00 PM
-  How far can we make sure the content in the table for time moves a bit more to the left?
- Or move the Title a bit more to the right, so a bit more space between. Makes it easier to comprehend for user

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/108995892-02ded380-769e-11eb-90aa-c3a19a66d322.png)

**Comment by lauren-mills** [comment]
I've found that it gets cut off with 12:00 - 12:30PM if I move it any more to the left, but I can add more spacing between the title and the time.

**Comment by Quirinevwm** [comment]
> I've found that it gets cut off with 12:00 - 12:30PM if I move it any more to the left, but I can add more spacing between the title and the time.

Yes probably with 22:33 - 22:34PM is even longer, good one let's just include a bit more spacing between time and title thanks!
