### ISSUE TITLE
[Calendar Skill V2] : multiple lined title event

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#631]
## Describe the bug
For a compact view I think we set on just showing it in 1 line as a pattern. Since how far will we make it possible to stretch?Complete titles could be very long and have multiple lines, are we just wrapping all of the title content? Or are we showing double spaced titles of meetings as a max?
Think double lined is oke, just not the complete show (so do cut it off after two lines) 

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/108996589-dbd4d180-769e-11eb-9e21-9a029591aa65.png)

**Comment by lauren-mills** [comment]
Set max lines to 2 for this textblock. I also removed the wrapping on the header text
