### ISSUE TITLE
[Calendar Skill V2] : Unknow error occured

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#632]
## Describe the bug
Error messaging 'Unknown error occured'

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/108996659-f149fb80-769e-11eb-9195-acbf6c750ef4.png)

**Comment by lauren-mills** [comment]
Can you provide more context on what you did before this error occurred?

**Comment by Quirinevwm** [comment]
> Can you provide more context on what you did before this error occurred?

Just scrolled back, was probably the card with 23 events (that you just fixed the load :))
![image](https://user-images.githubusercontent.com/43533472/109291681-88db5580-7829-11eb-8ef7-95333284a805.png)

**Comment by lauren-mills** [comment]
Ok, I'll close for now, but let me know if it happens again.
