### ISSUE TITLE
[Calendar Skill V2] : 'Update' SA

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#633]
## Describe the bug
SA show double reply, plus let's change order a bit (and update the content for 'Microsoft Teams' to 'Teams link' ):
- Order: Attendees, Date and time, Duration, Title, Description, Location, Teams link

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/108997403-d88e1580-769f-11eb-9da4-f21dcc0bf765.png)

**Comment by lauren-mills** [comment]
I've resolved the two cards issue, and will change the order.
