### ISSUE TITLE
Bot generation from template kept "emptyBot" instead of using project name in some places

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#636]
## Version
4.11.0

## Describe the bug
Using the "New Creation Flow" the generation of a new skill from the emptyBot template kept the name "emptyBot" in places where they were expected to be updated to use the project name instead.

For example, if I re-create whoSkill using the new flow:
- The main dialog is still called "emptyBot.dialog" instead of "whoSkill.dialog"
- References inside the emptyBot.dialog (that should be the whoSkill.dialog) still references "emptyBot.lg", "emptyBot.lu.qna", etc...

```
  "$schema": "https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/Composer/packages/server/schemas/sdk.schema",
  "generator": "emptyBot.lg",
  "id": "emptyBot",
  "recognizer": "emptyBot.lu.qna"
}
```

Whereas in the previous version of the creation flow this would have been the resulting part of the json:

```
  "$schema": "https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/Composer/packages/server/schemas/sdk.schema",
  "generator": "whoSkill.lg",
  "id": "whoSkill",
  "recognizer": "whoSkill.lu.qna"
}
```

## To Reproduce

1. Enable the "New Creation Flow" experience
2. Create a new bot using any project name but "emptyBot"

## Expected behavior

1. All the assets that have the word "emptyBot" should be replaced with project name (if necessary)

**Comment by ryanlengel** [comment]
The botName variable in generators handles this functionality, marking as resolved.
