### ISSUE TITLE
Empty bot template generation missing "recognizers" folder

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#642]
## Version
4.11.0

## Describe the bug
After creating a bot from the EmptyBot template from the adaptive runtime, switching a recognizer from Default to Regular Expression causes an ENOENT error because the "recognizers" folder is missing from the project folder.

## To Reproduce
1. Create a new EmptyBot project
2. Add a new trigger
3. Change the intent recognizer from Default to Regular Expression

## Expected behavior
No error

**Comment by ryanlengel** [comment]
The recognizers directory is included in generators now, markingas resolved.
