### ISSUE TITLE
LUIS application ID not found after creating project using EmptyBot template

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/botframework-components#643]
## Version
4.11.0

## Describe the bug
Adding a simple LUIS-based trigger fails with "'' is not a valid LUIS application ID." in the Emulator on first start up of the app.

## To Reproduce
1. Create a new chatbot using EmptyBot template with the New Bot Creation Flow
2. Add a simple trigger with utterance like "- Hello"
3. Add a "send response" action to the dialog flow
4. Configure the correct LUIS endpoint and authoring keys

## Expected behavior
Saying "Hello" in the bot should return the expected dummy response.

## Screenshots
![image](https://user-images.githubusercontent.com/9922190/109346037-ec638400-7825-11eb-8b1b-7e164c871015.png)
![image](https://user-images.githubusercontent.com/9922190/109346059-f4232880-7825-11eb-96e0-2f2328c33b8b.png)

**Comment by ryanlengel** [comment]
This issue has popped up again with the latest changes from the SDK, assigning to myself to monitor and I'll close when validated it's fixed.

**Comment by ryanlengel** [comment]
Resolved with latest SDK
