### ISSUE TITLE
Old conversational core template still listed

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#648]
If you turn off the new create flow feature flag, you'll see the old conversational core template listed. This needs to be cleaned up.

![image](https://user-images.githubusercontent.com/1139814/109363468-8258d800-7841-11eb-9ffb-d7e2754e419f.png)

**Comment by ryanlengel** [comment]
This is still listed but the old creation experience will be deprecated in R13, marking as resolved.
