### ISSUE TITLE
IsSkill should be false for root bot from calendar-assistant

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#659]
## Version
calendar-assistant generator as of 3/2/21

## Describe the bug
Inspecting the advanced settings for a multi bot generated for calendar-assistant, IsSkill seems to be set to true on the root bot and I think it should be false:

![image](https://user-images.githubusercontent.com/12264946/109605854-ce32a800-7af3-11eb-937b-8a34cbfd40b8.png)

## To Reproduce
1. Generate a multi bot using the calendar-assistant template
2. Got the Advanced Settings view for the root bot and check the SkillConfiguration section.

## Expected behavior
I believe IsSkill should be false for root bots.

**Comment by lauren-mills** [comment]
Done for enterprise assistant. Calendar assistant will be deprecated
