### ISSUE TITLE
LUIS App Name for generated bot should default to the project name

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#661]
## Version
latest from main as of 3/2/21

## Describe the bug
When you create a bot based on the calendar-assistant template, the LUIS application name defaults to "Assistant" and it should default the name of the main proj to help avoid collisions if you reuse LUIS app IDs.
![image](https://user-images.githubusercontent.com/12264946/109663890-96028800-7b3a-11eb-8239-7f82520ce76f.png)

Also, here is screenshot of the LUIS app name that gets set for a bot generated using Conversational Core:
![image](https://user-images.githubusercontent.com/12264946/109715701-f9f47300-7b71-11eb-925b-ccbf5af1f5ff.png)

## To Reproduce
1. Create a bot based on the calendar-assistant template
2. Check the LUIS app name in settings and see if that the LUIS app name is always Assistant.

## Expected behavior
I think it will be better if the LUIS Application name defaults to the name of the chosen bot

## Additional context
While this will work for a single dev, there will be collisions in a team environments where multiple devs are running the bot at the same time and sharing the same LUIS environments. 

There should be a way of letting each dev have a local configuration for LUIS that is not checked into source control so each developer can override the local settings and avoid collisions with other devs.

**Comment by benbrown** [comment]
Seen here
https://github.com/microsoft/botframework-components/blob/main/generators/generator-microsoft-bot-calendar-assistant/generators/app/templates/settings/appsettings.json#L30
