### ISSUE TITLE
Enterprise Assistant Template

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#670]
Friendly Name
Enterprise Assistant

Name
Microsoft.Bot.Template.EnterpriseAssistant

Description
A template for creating an assistant-style bot, designed for enterprise scenarios. Contains Calendar and Who as skills.

Purpose

<things>

Functionality

- Assistant Core
- Who
- Calendar

Open Questions

- Who is building this?

aka "Virtual Assistant in Composer"

**Comment by lauren-mills** [comment]
Enterprise assistant is out and aligned with assistant core template.
