### ISSUE TITLE
Chore: Prepare for components in multiple code languages

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#673]
We need to prepare for creating components in multiple code languages. We need to minimize duplication of shared assets, prepare the build pipeline, and ensure we can publish to npm with our official publishing pipeline.

## Folder structure

The current proposal is to structure like:

```
/packages
  /calendar
    /lg
    /dialog
    /csharp
      .sln
    /javascript
      .js
    readme.md 
```

## Build pipeline

Our build pipeline needs to create the NuGet and npm packages based on the finalized folder structure.

**Comment by peterinnesmsft** [comment]
This is back in scope per the Teams JS package. @joshgummersall let's sync on this - no major concern based on current PR but good just to make sure we're locked in the pattern.

**Comment by joshgummersall** [comment]
Note that the Teams package PR could be considered a P1 (rather than P0) for now. It's published and there are no pending changes yet going forward. We will need to resolve this once changes need to propagate out from the .NET package.

**Comment by peterinnesmsft** [comment]
js/dotnet split is added to Teams as a one-off case for now. We will need to formally revisit all-up for the repo. Moving back to backlog.

**Comment by tracyboehrer** [comment]
What is the complete list of action items for this?  Does it make sense to even do them in R14?
