### ISSUE TITLE
Orchestrator Component: Need to add ONNX and txt to artifacts

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/botframework-components#675]
## Version
4.13.0-preview

## Describe the bug
The current Adaptive Runtime allows only these files for publishing: 
```JSON
    <Content Include="**/*.blu;**/*.dialog;**/*.lg;**/*.lu;**/*.qna" Exclude="$(BaseOutputPath)/**;$(BaseIntermediateOutputPath)/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```
Orchestrator also needs `.onnx` and `.txt` added to this list - the language model itself is often published with the bot, and Orchestrator does not yet have a mechanism to download models at runtime.

## To Reproduce
Try publishing a bot with Orchestrator from Composer.  The resulting bot will fail because the zip file produced from the publish command is missing the `model.onnx` and `vocab.txt` files from the model publish folder.

## Expected behavior
`model.onnx` and `vocab.txt` will be in the zip file.

**Comment by clearab** [comment]
Probably want to be specific with the .txt include, rather than use **/*.txt

**Comment by peterinnesmsft** [comment]
Generator has been published and verified that the newly scaffolded .csproj has the additional content include globs.
