### ISSUE TITLE
HelpAndCancel: Split the Help and Cancel triggers/dialogs

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#681]
![image](https://user-images.githubusercontent.com/43043272/109877005-56659a00-7c27-11eb-8715-d8a977f05c5c.png)

The template has a single trigger for HelpAndCancel, which forwards to a HelpAndCancel dialog which triggers appropriately. Instead, these triggers should each have their own dialog and separate trigger in the root bot.

**Comment by gabog** [comment]
After this refactoring, I don't think the new Cancel and Help dialogs should have any utterances since those will be in the main dialog triggers
