### ISSUE TITLE
HelpAndCancel: Imported line appearing in LG

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#682]
Cancel has an "Imported" line appear but Help does not. Which is expected?

![image](https://user-images.githubusercontent.com/43043272/109878078-a133e180-7c28-11eb-81a3-4e4e0fc760cf.png)
![image](https://user-images.githubusercontent.com/43043272/109878091-a42ed200-7c28-11eb-9776-26d8b81de68b.png)

![image](https://user-images.githubusercontent.com/43043272/109878102-aa24b300-7c28-11eb-91f7-d7d5de772392.png)
![image](https://user-images.githubusercontent.com/43043272/109878112-ad1fa380-7c28-11eb-9bae-4bd7eca59c54.png)

**Comment by gabog** [comment]
I spoke to @benbrown and he mentioned this is added during import and is required for the uninstall. So closing this one.

There's another issue in composer where a new line gets added when importing and added it in composer [here](https://github.com/microsoft/BotFramework-Composer/issues/6419)
