### ISSUE TITLE
Remove schema and uischema from adaptive generator

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#694]
Previously the Composer runtime has had to make updates to the UI schema as demonstrated in https://github.com/microsoft/BotFramework-Composer/pull/4682

How do we keep this in sync and who owns it?

**Comment by tracyboehrer** [comment]
I believe no action is currently required for this.  Going to change the title to "Remove schema and uischema from adaptive generator" though and defer to a future release.

Composer will run dialog merge after the generation, which will update those files.
