### ISSUE TITLE
DRAFT: Define build process for Bot Host Application (Dialog Merge)

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#695]
Tom made a point that we should make sure to execute bf dialog:merge as part of the build process for the application to ensure we pick up any referenced dialog files.

In a general sense, we should evaluate what steps need to be performed as part of the application's build process, and implement that in some fashion using custom build targets, etc.

**Comment by tracyboehrer** [comment]
Closing in preference to keeping https://github.com/microsoft/BotFramework-Composer/issues/7741
