### ISSUE TITLE
Generators: Update README.md files to reflect current status.

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#718]

**Comment by peterinnesmsft** [comment]
@clearab to determine for all templates except for Enterprise Assistant; @lauren-mills can you take Enterprise Assistant?

**Comment by lauren-mills** [comment]
Enteprise assistant, calendar, and people readmes have all been updated.

**Comment by peterinnesmsft** [comment]
Still need updates to individual component package and root README.md files.
