### ISSUE TITLE
[R13] Feature: Empty Bot template

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#727]
### Summary
The empty template contains no dependencies other than the runtime, and contains only a root dialog, and a simple echo functionality. It replaces the existing empty & echo bot templates.

### Package Details
- **Package Name** - @microsoft/generator-bot-empty
- **Display Name** - Empty
- **Description** - TBD
- **Keywords** - TBD
- **Supported Languages** - C#
- **Supported Locales** - en-US

### Components
The following list of components should be referenced out of the box:

None.

### Additional Requirements
TBD

---

### Design and Engineering Items
The following tasks must be completed (create links to separate issues) for the feature to be considered design and code complete:

- [ ] Implement template
- [ ] Unit tests
- [ ] Onboard stub 0.0.0 package to npm
- [ ] Setup CI build and publish pipelines for package

---

### Acceptance Criteria
The following criteria must be met in order for the feature to be considered completed:

- [ ] Write acceptance criteria

**Comment by ryanlengel** [comment]
Empty bot template generator has been published.
