### ISSUE TITLE
[R13] Feature: Conversational Core template

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#729]
### Summary
The base bot that nearly all conversational bots that use a recognizer should be built from.

### Package Details
- **Package Name** - @microsoft/generator-bot-conversational-core
- **Display Name** - Conversational Core
- **Description** - TBD
- **Keywords** - TBD
- **Supported Languages** - C#
- **Supported Locales** - en-US

### Components
The following list of components should be referenced out of the box:

- **Help & Cancel**
  - **C# (NuGet)**: Microsoft.Bot.Components.HelpAndCancel-1.0.0
- **Welcome**
  - **C# (NuGet)**: Microsoft.Bot.Components.Welcome-1.0.0

### Additional Requirements
TBD

---

### Design and Engineering Items
The following tasks must be completed (create links to separate issues) for the feature to be considered design and code complete:

- [ ] Implement template
- [ ] Unit tests
- [ ] Onboard stub 0.0.0 package to npm
- [ ] Setup CI build and publish pipelines for package

---

### Acceptance Criteria
The following criteria must be met in order for the feature to be considered completed:

- [ ] Write acceptance criteria

**Comment by ryanlengel** [comment]
Conversational Core template generator has been published.
