### ISSUE TITLE
[R13] Feature: Disambiguation

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-components#737]
### Summary
The "duplicated intents recognized" trigger should be enabled in the root dialog of Assistant Core and/or added for other bots when skill bots are added. With this enabled in a template, it should just work for Luis, QnA, and Orchestator. There are a couple of issues on Orchestator that should enabled it:
- #580 Utterance is not passed to skill if disambiguation kicks in at parent 
- microsoft/BotFramework-Composer#5747 ChooseIntent (aka Duplicate Intent) Trigger doesn't work when using Orchestrator

![image](https://user-images.githubusercontent.com/43043272/110728768-73274200-81d2-11eb-9d77-f7816347ab40.png)
![image](https://user-images.githubusercontent.com/43043272/110728809-83d7b800-81d2-11eb-927c-75516504a580.png)

### Components
The following list of components should be referenced out of the box:

None.

### Additional Requirements
TBD

---

### Design and Engineering Items
The following tasks must be completed (create links to separate issues) for the feature to be considered design and code complete:

- [x] Tracking Orchestrator bug at microsoft/BotFramework-Composer#5747
- [x] Implement in Assistant Core template
- [ ] Tracking duplicated intents dialog bug at microsoft/BotFramework-Composer#6431
---

**Comment by clearab** [comment]
@ryanlengel the Orchestrator bug associated with this has been closed - what is remaining to get this across the finish line?

**Comment by taicchoumsft** [comment]
Hi @clearab , The composer PR enables disambiguation for Orchestrator, but the disambiguation template is slightly broken.  I'm working on the template to make it work across QnA, Luis and Orchestrator, I'll get it done in the next few days.

**Comment by ryanlengel** [comment]
Tai's issue is being tracked at microsoft/botframework-composer#6431
