### ISSUE TITLE
update-schemas.sh should use the bash executable defined in the user's path

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/botframework-components#757]
https://github.com/microsoft/botframework-components/blob/08f5da307b417710e1762ee4518c5f9ce6fe0557/generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/update-schema.sh#L1

The shebang should be `#!/usr/bin/env bash` which will look for `bash` in the user's path.

**Comment by tracyboehrer** [comment]
Closed by #851
