### ISSUE TITLE
schema update scripts need to be updated for usage in projects created with yeoman

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/botframework-components#759]
They currently reference a `$runtime` variable which looks obsolete in the yeoman generated project.

**Comment by a-b-r-o-w-n** [comment]
To add to this, even after removing the references to `$runtime` I am unable to produce a merged schema in a project created with yeoman.

**Comment by a-b-r-o-w-n** [comment]
I was able to get a merged schema by escaping the `!` in the args to `bf dialog:merge`.

```bash
bf dialog:merge "*.schema" "\!sdk-backup.schema" "*.uischema" "\!sdk-backup.uischema" "\!sdk.override.uischema" "../*.csproj" -o $SCHEMA_FILE
```

**Comment by peterinnesmsft** [comment]
@tracyboehrer I believe this was taken care of with your recent changes here. Can you confirm and close out if applicable?

**Comment by tracyboehrer** [comment]
Confirmed.  By #859.  See also #943.
