### ISSUE TITLE
Update R13 templates to have support for JS/dotnet and webapp/functions

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-components#765]
Creating an issue to track all the work needed to get preview generators that are working with every combination node/dotnet and js/csharp published in a preview setting and usable in Composer

1. Get the status of all generator combination below to green and working e2e in Composer
2. Update and publish adaptive bot generator as a preview package (indication of preview TBD - probably a tag)
3. Update Empty Bot and Conv Core generators to use latest published adaptive bot generator package. 
4. Publish empty bot and Conv Core generator as preivew packages
5. **[not blocked by prev steps]** Implement hidden feature flag that triggers whether or not preview generators are pulled into Composers template selection view

**Status of generators**
- Empty Bot
  - DotNet
    - [ ] Functions: Dependecies not declared in MessagesTrigger.cs + other things breaking ability to build functions
    - [ ] Web App: working after Gabos fix is in
  - Node 
     - [x] Functions: generation and local run in Composer
       - [x] Provision & publishing working 
       - [ ] Able to talk to bot after publish
     - [x] WebApp: Working in Composer
       - [x] Provision & publishing working 
       - [ ] Able to talk to bot after publish 
- Conversational Core
  - DotNet
    - [ ] Functions: Dependecies not declared in MessagesTrigger.cs + other things breaking ability to build functions
    - [ ] Web App: working after Gabos fix is in
  - Node 
     - [x] Functions: Working in Composer
       - [x] Provision & publishing working 
       - [ ] Able to talk to bot after publish
     - [x] WebApp: Working in Composer
       - [x] Provision & publishing working 
       - [ ] Able to talk to bot after publish

**Comment by peterinnesmsft** [comment]
@pavolum what is the current status of this item?

**Comment by peterinnesmsft** [comment]
This is for tracking test scenario owners and coverage - tracking in internal team documents.
