### ISSUE TITLE
Enterprise Assistant should support OAuth dialog configured out of the box

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/botframework-components#778]

**Comment by lauren-mills** [comment]
Unsure what the specific request is here. I have included the steps for configuring the authentication settings in the readme for each of the templates. If we are asking to have those scopes automatically assigned I don't have an entry point to do that through the creation experience right now.

If this is for setting up SSO between the root bot and skills, there was some discussion about the right way to accomplish this, so we should get some feedback from the SDK team on the recommended approach for setting it up.

**Comment by lauren-mills** [comment]
@carlosscastro, @peterinnesmsft, @clearab - what is the ask/guidance here?

**Comment by lauren-mills** [comment]
Closing this due to ambiguity. We can open an new issue once we have a more clear requirement.
