### ISSUE TITLE
LG content within templates needs to use Structure Responses

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-components#790]
Currently our templates use the " - " notation to specifying multiple responses, but this does not allow the user to use the new LG Editor capability within Composer.  Responses within templates should be updated to use Structured Responses (i.e. Activity templates) instead, which will ensure the default experience is the LG response editor.

**Comment by ryanlengel** [comment]
Tracking for Conversation Core, Assistant Core, Enterprise Assistant

**Comment by ryanlengel** [comment]
This is the case for the above root bot templates, for PbX Skills we need to sync after this release on aligning best practices.
