### ISSUE TITLE
Empty bot throws duplicate file error on schema merge

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#858]
# Overview
I believe during the Composer build process a /generated/interruptions folder is getting added that contains duplicate files, which then breaks schema merge.

# Steps to reproduce

1. Create a new empty bot
2. Start, then stop your bot
3. Go to package manager, see error:

```
If this problem persists, please file an issue on GitHub
Details
Could not load component list:Error multiple definitions of empty.en-us.lu in d:\trash\empty\empty\generated\interruption\empty.en-us.lu d:\trash\empty\empty\language-understanding\en-us\empty.en-us.lu Error multiple definitions of empty.en-us.qna in d:\trash\empty\empty\knowledge-base\en-us\empty.en-us.qna d:\trash\empty\empty\generated\interruption\empty.en-us.qna Error must have a merged .schema to merge .uischema files *** Could not merge components ***
```

**Comment by benbrown** [comment]
Hrrm! There may be some change needed to the call to schema merge to exclude those generated files... they *should* already be excluded, but there was a recent change to the schema merge library.

**Comment by clearab** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/6855

**Comment by peterinnesmsft** [comment]
@benbrown can this issue be closed?

**Comment by clearab** [comment]
I haven't hit this one with the dialog:merge changes, I think it can be?
