### ISSUE TITLE
dotnet functions template outputs a controller, not triggers

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-components#868]
## Version

1.0.rc3

## Describe the bug

When you select dotnet and functions it creates a project which has controllers, no triggers, and is not a valid functions project.

## To Reproduce

Create new bot using DOTNET and FUNCTIONS

## Expected behavior

To get a valid functions project that runs.

**Comment by ryanlengel** [comment]
This is resolved in `rc4` 

![image](https://user-images.githubusercontent.com/43043272/114242221-60be3680-993f-11eb-8427-66c055473150.png)
