### ISSUE TITLE
Adaptive.Teams package doesn't contain uischema

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#872]
This package doesn't seem to contain any uischema to organize the actions / triggers it adds, so they are getting dropped into the default "Custom Actions" / "Action Triggers" sections.

I think we have two options:
- Single "Teams" menu
- Break it down to
  - Teams - Get Info
  - Teams - Messages
  - Messaging Extension
  - Task Modules & Tabs

**Comment by peterinnesmsft** [comment]
Removing @carlosscastro and @vivekkshankar from assignees and solely to @EricDahlvang. Spoke offline - this needs to land for R13. Current ETA is for 4/28 for inclusion in RC7.
