### ISSUE TITLE
New "Blank Bot", called "empty_1" greets as "EmptyBot sample"

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-components#895]
Create a new Blank Bot, named (the default) "empty_1". 

When run in Emulator, the bot greets as "EmptyBot sample". 

The template(s) should update this as part of install. Defaulting to the name would be resonable, or prompting me for a "Friendly" name would be more reasonable. 

## Describe the bug

The Bot Name is hardcoded in the LG file, and not templatized on the Bot Name that I choose. 

## Version

Blank Bot template: 1.0.0-rc3

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Blank Bot
2. Give it a name (or accept the default)
2. Run it. 
3. Connect to it via Web Chat.
4. Observe the greeting is incorrect, as it's hardcoded to "EmptyBot sample" in the LG file. 

## Expected behavior

Update the LG file on installation based on the name I choose. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114789619-3e119080-9d38-11eb-8987-1781a4bbc19c.png)

![image](https://user-images.githubusercontent.com/1165321/114789725-67cab780-9d38-11eb-95ff-dd1715798b60.png)

**Comment by clearab** [comment]
I'm guessing this is probably true across templates, since we re-use. Let's change the package and the generator wording to be completely container agnostic - so "Welcome to your bot" or similar.

**Comment by ryanlengel** [comment]
Agreed, I'll take a pass at this and the other generators and make sure they're agnostic

**Comment by ryanlengel** [comment]
@clearab Conversation/Core Assistant/Enterprise Assistant are ok, they use:
```
# WelcomeNewUser
- 🖐️ Hey, there! How can I help you today?
- 🖐️ Hi! How can I help?
- 🖐️ Hello! What do you want to do today?

# WelcomeReturningUser
- 🖐️ Welcome back! How can I help you today?
- 🖐️ Hello again! What can I help with?
- 🖐️ Good to see you again. What do you want to do today?
- 🖐️ Hey, there! Let's get started.
- 🖐️ Hello again! How can I help?
```

For Empty we can either stick with a plain "Welcome to your bot" or add some variety and use the WelcomeNewUser template. Given that it is supposed to be the most "empty" bot which would you prefer?

**Comment by clearab** [comment]
@ryanlengel  use "Welcome to your bot" please, with no template.
