### ISSUE TITLE
New "Blank Bot" doesn't greet, despite having a greeting

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-components#898]
Created a "Blank bot" using the template. The template says:

> [...] creates a bot containing only a root dialog and a **initial greeting dialog**.

Note: I personally understand that responding to "hello" isn't the type of greeting described in the template, nor is it how the bot is triggered to respond. However, **this is a very subtle thing**, and users (like myself) will **EXPECT** the bot to respond to "Hello / Hi" because it's described as having a greeting dialog, and "Hello" is a greeting. This behavior makes this a pure UX bug.

![image](https://user-images.githubusercontent.com/1165321/114788831-048c5580-9d37-11eb-8f90-85e40c865d46.png)

## Describe the bug

Created the bot. Hit run. Opened Webchat. 

No greeting! See Screen shot. 

![image](https://user-images.githubusercontent.com/1165321/114788847-0c4bfa00-9d37-11eb-9110-342a98e784ee.png)

The greeting plumbing is setup, it's just not working. 
![image](https://user-images.githubusercontent.com/1165321/114788898-21288d80-9d37-11eb-8488-1e3d01005f28.png)

## Version
Blank bot 1.0.0-rc3

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Blank Bot. 
2. Hit Run.
3. Open the Webchat.
4. Say "hello" 
5. Observe nothing happens
6. Fail to grok why "Greeting Dialog" as described in the description doesn't enable the bot to participate in a "Greeting Dialog".

## Expected behavior

Basic greeting and other behaviors, per the template description. 

Restarting the Bot, and restarting the conversation both fail to improve anything.

**Comment by peterinnesmsft** [comment]
@clearab I assume this is being worked on as part of README updates. Feel free to update to reflect correct status if that is not accurate.

**Comment by clearab** [comment]
This one is actually an SDK bug based on the label for the ConversationUpdate trigger - https://github.com/microsoft/botbuilder-dotnet/issues/5502

**Comment by clearab** [comment]
However, the readme will be updated to more accurately reflect the capability as well
