### ISSUE TITLE
UpdateSchema PowerShell & Bash scripts

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#900]
In the /schema folder we have .ps1 and .sh scripts that seem to be for running dialog:merge. Manually running the scripts doesn't seem to work - are these still needed? Can we update them to work with the current structure/command? They would be useful for the 'extend with code' scenario, so hopefully we don't have to explain how to use dialog:merge...

**Comment by clearab** [comment]
I was able to manually run the dialog:merge portion of the ps1 script - not super used to debugging powershell so maybe the issue is just in the schema backup file / restore logic.

**Comment by peterinnesmsft** [comment]
@clearab can you confirm what directory you were running the script from? Are you able to repro, and if so, provide the output from running them?

**Comment by peterinnesmsft** [comment]
Closing as I don't think there is a functional regression here outside of running from the right directory. If there's a particular issue that can be reproduced that needs to be addressed, re-open and we can triage.
