### ISSUE TITLE
/schema folder readme is outdated/wrong

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#903]
This readme needs to be updated to reflect the current process for updating your schema files, and also talk about packages.

https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-adaptive/generators/app/templates/assets/schemas

**Comment by peterinnesmsft** [comment]
@clearab assigning this one to you as part of README updates. I'm assuming this will come with the various updates on READMEs - feel free to update as necessary.

**Comment by tracyboehrer** [comment]
Do we have docs on schema and uischema?  This readme gives some details, but it's light.

**Comment by clearab** [comment]
Nope, no docs on either that I'm aware of
