### ISSUE TITLE
Custom package installation issue using the version

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/botframework-components#913]
Version
SDK Version : 4.13.0-rc2

Bot Framework Composer version

Version: 1.4.0-nightly.234969.d950804
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Describe the bug
Not able to install custom package.

A problem occured during the install of this Component: Error C:\Users....nuget\packages\microsoft.bot.builder.dialogs.adaptive\4.8.0-rc0\content\Schemas\Dialogs\Microsoft.Ask.schema: Does not support allOf in component .schema definitions Error

C:\Users....nuget\packages\microsoft.bot.builder.dialogs.adaptive\4.8.0-rc0\content\Schemas\TriggerConditions\Microsoft.OnRepromptDialog.schema: Does not support allOf in component .schema definitions Error

Does not support allOf in component .schema definitions Error must have a merged .schema to merge .uischema files Could not merge components

To Reproduce
Use the package version "1.0.0" this issue gets raised. If use the version "0.0.1" no issues

Shared video with @clearab

**Comment by pavolum** [comment]
@rvinothrajendran we are looking into this and attempting to repro

**Comment by pavolum** [comment]
To confirm, you experience this when using a custom package you developed yourself correct?

**Comment by rvinothrajendran** [comment]
@pavolum yes

**Comment by peterinnesmsft** [comment]
@rvinothrajendran based on the snippets you have provided, it looks like you are resolving against quite a stale non-stable version of Microsoft.Bot.Builder.Dialogs.Adaptive (4.8.0-rc0). If you are creating a new bot with the recent nightly builds, you ought to be targeting 4.13.0 GA.

Is there a particular reason you're targeting that older version? If not, I would suggest clearing your package cache and double-checking your dependency version ranges.

**Comment by rvinothrajendran** [comment]
@peterinnesmsft I did not target older version , when I was tried its refer the 4.13.0-rc2 and based on the version I got the error ( which I have mentioned in the issue) .. If no issue creating package from your end then please close this issue.
