### ISSUE TITLE
'People' example actions have no context follow ups & guidance in response 'unauthorized' WebChat test

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#914]
## Version
enterprise_assistant (template, 14 april 2021)
![image](https://user-images.githubusercontent.com/43533472/115023167-b1dda580-9ebe-11eb-8a61-adb176341173.png)

## Describe the bug
 - 'You can ask me' follow up in Enterprise template -> clicking on 'People' then the example utterances are clickable with no effect (they never will since no contact name was given). Maybe make the actions unclickable more like informational for this step. 
*Since the actions after People have no effect they will only result in error, or will it follow up with **who** do you mean? 
*For 'Calendar' utterances would be actionable after auth, so no need to make them non clickable. (do consider adding guidance, see next bullet) 
 
When a user decides to open up the 'Enterprise template' without reading the guidance set-up before:
 - Can we communicate guidance in the error message "unauthorized", maybe direct to your setup guidelines: https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-enterprise-assistant/generators/app/templates

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/115020545-0717b800-9ebb-11eb-96ef-37a414b6b1b5.png)

**Comment by lauren-mills** [comment]
Updated the examples in the bot tour in #991
