### ISSUE TITLE
Try out 'Calendar' after 'People' in 'You can ask me about' in Enterprise template

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-components#915]
## Version
enterprise_assistant (template, 14 april 2021)
![image](https://user-images.githubusercontent.com/43533472/115023190-bace7700-9ebe-11eb-8ea8-fe3394e35e9a.png)

## Describe the bug
Testing inside Composer, I looked for what 'People' can do for me. Then I wanted to explore what 'Calendar' could. The returning action is not supported, it would be great to then follow-up in the bot to show what Calendar supports with example utterances.

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/115022484-be153300-9ebd-11eb-9180-c956da205f82.png)

**Comment by lauren-mills** [comment]
The error should be handled by the allowedCallers, and I updates the button text with names so that they will be correctly recognized by the skill 

fixed by #991
