### ISSUE TITLE
Teams Trigger Naming in form editor

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-components#923]
The highlighted section below should be the name of the component like "Teams.OnMEFetchTask". The reason for that is that developers can rename the title of the block from "Teams messaging extension fetch task" to something like "Show quote popup" and you want to be able to still able to tell what type of trigger it is. That subtitle is the only way to do that. Plus in this example the subtitle is simply re stating what's in the description.

![](https://user-images.githubusercontent.com/698939/115095499-7058f480-9ed6-11eb-869d-5f4b353d73ac.png)

**Comment by Stevenic** [comment]
For example:  

![](https://user-images.githubusercontent.com/698939/115095867-b2366a80-9ed7-11eb-8f76-f89df26254ad.png)

**Comment by peterinnesmsft** [comment]
@EricDahlvang I'm assuming this should be postponed to R14. Let me know if you have cycles otherwise and we can evaluate if this needs to land for this release.

**Comment by peterinnesmsft** [comment]
Spoke offline with @EricDahlvang - this will be included for R13. Current ETA is for 4/28 for inclusion in RC7.
