### ISSUE TITLE
Teams triggers don't need to repeat the word "Teams" in all of the trigger names

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-components#924]
You're very clearly adding a Teams specific trigger so need to repeat the word "Teams" in every trigger.

![](https://user-images.githubusercontent.com/698939/115096066-88317800-9ed8-11eb-8406-b7705cd565f5.png)

**Comment by yeze322** [comment]
Needs to edit the `label` field in uischema files. These labels are quried from sdk.schema
https://github.com/microsoft/botframework-components/blob/7ff61c6a9712bd35ab6da543ec8575cd41727f11/packages/Teams/Schemas/TriggerConditions/Teams.OnTeamRestored.schema#L4

Edit [OnTeamsRestored.uischema](https://github.com/microsoft/botframework-components/blob/main/packages/Teams/Schemas/TriggerConditions/Teams.OnTeamRestored.uischema)
```
{
    "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
    "trigger": {
      "submenu": "Microsoft Teams"
    }
}
```
to
```
{
    "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
    "trigger": {
      "label": "On team restored",
      "submenu": "Microsoft Teams"
    }
}
```
