### ISSUE TITLE
Deploy.ps1 is out of date for the R13 runtime folder structure

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#952]
The [scripts/deploy.ps1](https://github.com/microsoft/botframework-components/blob/main/generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/Scripts/deploy.ps1) script in the composer project is using the old runtime structure and needs to be updated to work with the new folder structure. 

Note, if this doesn't get addressed for R13 we will need to remove the scripts folder from the template (it doesn't currently work with the current folder structure), I think this script is referenced in docs so we will need to address that too if we delete it

**Comment by boydc2014** [comment]
@GeoffCoxMSFT is this something you can help take a look?

**Comment by peterinnesmsft** [comment]
Labelling as P0 for shiproom consideration. As the Deploy.ps1 scripts are holdovers from the old Virtual Assistant, group consensus is to just remove these from the templates. We do not anticipate any breaks in behavior due to new provisioning and publishing flows in Composer.
