### ISSUE TITLE
[Bugbash 4/22] People README needs a refresh and copy edit

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botframework-components#966]
The README for this template, as it is rendered in Composer, has a few issues:
1. The **Configure Authentication** heading and initial paragraph appear twice.
2. The first step under **Using Azure Portal** references an ambiguous resource and outdated Azure UI.
    -  Should be something like, "Open your **Azure Bot** resource and select **Configuration** under **Settings**.

Not sure what the URL of the content is that Composer is rendering. Here's a screen shot:

![image](https://user-images.githubusercontent.com/35047199/115790302-5ce8d600-a37b-11eb-9913-b3bf0fe77103.png)

![image](https://user-images.githubusercontent.com/35047199/115790259-4fcbe700-a37b-11eb-9ea3-dd215b0ebee4.png)

**Comment by peterinnesmsft** [comment]
@lauren-mills @thomas-chung can you please take a look?

**Comment by thomas-chung** [comment]
Sure thing!

**Comment by lauren-mills** [comment]
Already in progress PR #965

**Comment by lauren-mills** [comment]
Closed by #965
