### ISSUE TITLE
Schema for graph api is completely wrong for structured properties.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-components#969]
## Version

looking at code, rc-latest

## Describe the bug

The .schema definitions for graph APIs does not match the property definition at all

## To Reproduce

Look at composer (Create event for instance)

You see this:

![](https://user-images.githubusercontent.com/17789481/115805247-68e39080-a399-11eb-83f4-c4a77f626332.png)

But the definition in the code is this:

![](https://user-images.githubusercontent.com/17789481/115805384-b52ed080-a399-11eb-8674-383f34d046b9.png)

This is a structured object. It's not a string, or number, or array or a boolean. 

This mismatch is because the .schema is completely wrong.

```
"eventToCreateProperty": {
      "$ref": "schema:#/definitions/valueExpression",
      "title": "New event",
      "description": "Event object to create.",
      "examples": []
    },
```

It's not a valueexpression.  A valueexpression says ANY object type is acceptable including value types.  This is not true.

The minimum schema should be declaring it's an `"schema:#/definitions/objectExpression",`

As that would tell the UI to at least put an object editor (json editor there.)

Better yet, tell us the shape of the object by providing a default object.  Here is a .schema for ConversationREference property:

```
  "conversationReference": {
          "$ref": "#/definitions/objectExpression",
          "title": "Conversation Reference",
          "description": "A conversation reference. (NOTE: Minimum required values or channelId, conversation).",
          "examples": [
            {
              "channelId": "skype",
              "serviceUrl": "http://smba.skype.com",
              "conversation": {
                "id": "11111"
              },
              "bot": {
                "id": "22222"
              },
              "user": {
                "id": "33333"
              },
              "locale": "en-us"
            }
          ]
        },
```

## Expected behavior

make it objectExpression with a examples:

**Comment by lauren-mills** [comment]
@tomlm Does the SDK team have a document outlining these best practices?
