### ISSUE TITLE
Examples in .schema are completely meaningless

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-components#971]
## Version

latest All of the component .schemas are missing valid examples, 

## Describe the bug

all of the component packages .schemas are missing **examples** field, and so they all display this:

![](https://user-images.githubusercontent.com/17789481/115805973-da700e80-a39a-11eb-9114-994128644399.png)

Hello ${user.name}  is kind of insulting to the consumer, because it's right in your face that we didn't care enough to fix a glaring bug like this.  

## To Reproduce

Look at composer graph component package.

## Expected behavior

There should be valid examples defined for every property that help the user to propertly fill it out.

**Comment by lauren-mills** [comment]
"Hello ${user.name}" must just be the default because we don't have examples for a lot of things. We can add this

**Comment by tomlm** [comment]
Examples are an opportunity to show an example **values** are.  Using expression as examples should only be used if that is the primary mechanism and there is no useful information  that can be expressed for them.

Here's an example that would be really useful:

   "Examples": \[

{  

    ... example object

} 

    \]

**Comment by thomas-chung** [comment]
Keeping issue open until we know it's fully resolves
