### ISSUE TITLE
Graph Component actions don't group their actions by category

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-components#972]
## Version

latest

## Describe the bug

![](https://user-images.githubusercontent.com/17789481/115806236-39358800-a39b-11eb-8796-3790a22e69e8.png)

These are all lumped into "Custom Actions". 

## To Reproduce

Add Graph package and Look at composer

## Expected behavior

These should be grouped into "Graph" menu, and then sub grouped into "Contacts, Events, etc" like teams package does

![](https://user-images.githubusercontent.com/17789481/115806317-63874580-a39b-11eb-93aa-988286f486e2.png)

**Comment by lauren-mills** [comment]
Hi @tomlm we have a PR to group them into a Microsoft Graph submenu. Do to the difficulties with updating the uischema later (per @clearab) we are not going to split them further at this time because we think we may need to move things around a bit in the next iteration.

**Comment by lauren-mills** [comment]
PR #962

**Comment by lauren-mills** [comment]
Merged
