### ISSUE TITLE
Rename sdk.schema to app.schema

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-components#998]
I believe sdk.schema and sdk.uischema should be renamed to bot.schema, or {app_name}.schema.

**Comment by lauren-mills** [comment]
There is another issue that was raised by @tomlm that says app.schema is the standard #781

**Comment by tracyboehrer** [comment]
This probably has some tentacles.  For example, it's in update-schema scripts, and when I did a search in the Composer branch, sdk.schema is referenced.

**Comment by cwhitten** [comment]
Composer currently accepts both app.schema/uischema & sdk.schema/uischema, with "app" taking priority.

**Comment by ryanlengel** [comment]
Closing, duplicate of #781. I will copy over any relevant content here to there.
